import {
  OrganizationSubscription,
  PlanLimits,
  SubscriptionInvoice,
  SubscriptionPayment,
  SubscriptionPlanRecord,
} from '../models/subscription.model';

export const SUBSCRIPTION_WORKSPACE_HEADER = {
  eyebrow: 'Subscription & Billing',
  title: 'Your subscription',
  description: 'View plan limits, usage, invoices, and upgrade or renew your commercial plan.',
};

export function createLimits(partial: Partial<PlanLimits>): PlanLimits {
  return {
    projects: partial.projects ?? 0,
    buildings: partial.buildings ?? 0,
    units: partial.units ?? 0,
    owners: partial.owners ?? 0,
    staff: partial.staff ?? 0,
    storageGb: partial.storageGb ?? 0,
    monthlyNotifications: partial.monthlyNotifications ?? 0,
    whiteLabel: partial.whiteLabel ?? false,
    advancedReports: partial.advancedReports ?? false,
    prioritySupport: partial.prioritySupport ?? false,
    apiAccess: partial.apiAccess ?? false,
    customDomain: partial.customDomain ?? false,
  };
}

export const DEFAULT_PLANS: readonly SubscriptionPlanRecord[] = [
  {
    id: 'plan-free-trial',
    code: 'free_trial',
    name: 'Free Trial',
    description: 'Time-boxed trial for new builder organizations.',
    tier: 'free_trial',
    billingInterval: 'monthly',
    currency: 'INR',
    monthlyPriceMinor: 0,
    annualPriceMinor: 0,
    active: true,
    public: true,
    trialDays: 14,
    sortOrder: 10,
    features: ['Trial access', 'Limited projects', 'Email support'],
    limits: createLimits({
      projects: 2,
      buildings: 4,
      units: 50,
      owners: 50,
      staff: 3,
      storageGb: 5,
      monthlyNotifications: 50,
    }),
  },
  {
    id: 'plan-starter',
    code: 'starter',
    name: 'Starter',
    description: 'For emerging builder organizations.',
    tier: 'starter',
    billingInterval: 'monthly',
    currency: 'INR',
    monthlyPriceMinor: 14900,
    annualPriceMinor: 149000,
    active: true,
    public: true,
    trialDays: 0,
    sortOrder: 20,
    features: ['Project management', 'Owner assignment', 'Document upload'],
    limits: createLimits({
      projects: 5,
      buildings: 15,
      units: 200,
      owners: 200,
      staff: 10,
      storageGb: 50,
      monthlyNotifications: 500,
    }),
  },
  {
    id: 'plan-professional',
    code: 'professional',
    name: 'Professional',
    description: 'Scale with branding and higher limits.',
    tier: 'professional',
    billingInterval: 'monthly',
    currency: 'INR',
    monthlyPriceMinor: 39900,
    annualPriceMinor: 399000,
    active: true,
    public: true,
    trialDays: 0,
    sortOrder: 30,
    features: ['White-label branding', 'Priority support', 'Advanced reports'],
    limits: createLimits({
      projects: 25,
      buildings: 100,
      units: 2000,
      owners: 2000,
      staff: 50,
      storageGb: 250,
      monthlyNotifications: 5000,
      whiteLabel: true,
      advancedReports: true,
      prioritySupport: true,
    }),
  },
  {
    id: 'plan-enterprise',
    code: 'enterprise',
    name: 'Enterprise',
    description: 'Custom limits and dedicated success.',
    tier: 'enterprise',
    billingInterval: 'annual',
    currency: 'INR',
    monthlyPriceMinor: 0,
    annualPriceMinor: 0,
    active: true,
    public: true,
    trialDays: 0,
    sortOrder: 40,
    features: ['Custom limits', 'Dedicated success', 'API access', 'Custom domain'],
    limits: createLimits({
      projects: 9999,
      buildings: 9999,
      units: 9999,
      owners: 9999,
      staff: 9999,
      storageGb: 9999,
      monthlyNotifications: 999999,
      whiteLabel: true,
      advancedReports: true,
      prioritySupport: true,
      apiAccess: true,
      customDomain: true,
    }),
  },
  {
    id: 'plan-custom',
    code: 'custom',
    name: 'Custom Plan',
    description: 'Negotiated commercial agreement for strategic builders.',
    tier: 'custom',
    billingInterval: 'custom',
    currency: 'INR',
    monthlyPriceMinor: 0,
    annualPriceMinor: 0,
    active: true,
    public: false,
    trialDays: 0,
    sortOrder: 50,
    features: ['Negotiated limits', 'Custom SLA', 'Dedicated onboarding'],
    limits: createLimits({
      projects: 100,
      buildings: 400,
      units: 10000,
      owners: 10000,
      staff: 200,
      storageGb: 2048,
      monthlyNotifications: 50000,
      whiteLabel: true,
      advancedReports: true,
      prioritySupport: true,
      apiAccess: true,
    }),
  },
];

export const MOCK_SUBSCRIPTIONS: readonly OrganizationSubscription[] = [
  {
    id: 'sub-demo-001',
    organizationId: 'org-builder-demo',
    planId: 'plan-professional',
    planCode: 'professional',
    planName: 'Professional',
    status: 'active',
    billingInterval: 'annual',
    currency: 'INR',
    amountMinor: 399000,
    startedAt: '2025-08-01T00:00:00Z',
    currentPeriodStart: '2025-08-01T00:00:00Z',
    currentPeriodEnd: '2026-08-01T00:00:00Z',
    renewsAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
  },
];

export const MOCK_INVOICES: readonly SubscriptionInvoice[] = [
  {
    id: 'inv-demo-1001',
    organizationId: 'org-builder-demo',
    subscriptionId: 'sub-demo-001',
    invoiceNumber: 'INV-2026-1001',
    status: 'paid',
    currency: 'INR',
    subtotalMinor: 399000,
    taxMinor: 71820,
    totalMinor: 470820,
    issuedAt: '2025-08-01T00:00:00Z',
    dueAt: '2025-08-15T00:00:00Z',
    paidAt: '2025-08-02T00:00:00Z',
    pdfUrl: undefined,
    notes: 'Annual Professional plan',
  },
];

export const MOCK_PAYMENTS: readonly SubscriptionPayment[] = [
  {
    id: 'pay-demo-1001',
    organizationId: 'org-builder-demo',
    subscriptionId: 'sub-demo-001',
    invoiceId: 'inv-demo-1001',
    amountMinor: 470820,
    currency: 'INR',
    paymentStatus: 'succeeded',
    paymentMethod: 'bank_transfer',
    transactionReference: 'TXN-HB-1001',
    providerCode: 'manual',
    paidAt: '2025-08-02T00:00:00Z',
    notes: 'Manual collection recorded',
    createdAt: '2025-08-02T00:00:00Z',
  },
];

export function formatMoney(amountMinor: number, currency = 'INR'): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency,
    maximumFractionDigits: 0,
  }).format(amountMinor / 100);
}
