import {
  AuditLogRecord,
  HealthScoreSnapshot,
  HealthServiceRecord,
  IncidentRecord,
  MonitoringMetric,
  OpsAlertRecord,
  OpsNavItem,
  QueueJobStatus,
  TelemetryProviderPlaceholder,
  TimelineEvent,
  OpsUserActivityRecord,
} from '../models/operations-admin.model';

export const OPS_SECTIONS: readonly OpsNavItem[] = [
  {
    id: 'dashboard',
    label: 'Overview',
    description: 'Executive operations summary',
    icon: 'pi pi-th-large',
    route: '/super-admin/operations',
  },
  {
    id: 'health',
    label: 'Health',
    description: 'Service and platform health',
    icon: 'pi pi-heart',
    route: '/super-admin/operations/health',
  },
  {
    id: 'audit',
    label: 'Audit Logs',
    description: 'Immutable activity audit trail',
    icon: 'pi pi-book',
    route: '/super-admin/operations/audit',
  },
  {
    id: 'activity',
    label: 'User Activity',
    description: 'Logins, sessions, and security events',
    icon: 'pi pi-users',
    route: '/super-admin/operations/activity',
  },
  {
    id: 'monitoring',
    label: 'Monitoring',
    description: 'Performance and resource signals',
    icon: 'pi pi-chart-line',
    route: '/super-admin/operations/monitoring',
  },
  {
    id: 'alerts',
    label: 'Alerts',
    description: 'Incidents and operational alerts',
    icon: 'pi pi-bell',
    route: '/super-admin/operations/alerts',
  },
];

export const MOCK_HEALTH_SERVICES: readonly HealthServiceRecord[] = [
  {
    id: 'svc-app',
    name: 'Application',
    category: 'application',
    status: 'healthy',
    latencyMs: 42,
    uptimePercent: 99.98,
    lastCheckedAt: '2026-07-14T07:55:00Z',
    message: 'All web shells responding normally.',
  },
  {
    id: 'svc-db',
    name: 'Database',
    category: 'database',
    status: 'healthy',
    latencyMs: 18,
    uptimePercent: 99.95,
    lastCheckedAt: '2026-07-14T07:55:00Z',
    message: 'Primary pool healthy. Replica lag 120ms.',
  },
  {
    id: 'svc-auth',
    name: 'Authentication',
    category: 'auth',
    status: 'degraded',
    latencyMs: 210,
    uptimePercent: 99.4,
    lastCheckedAt: '2026-07-14T07:54:00Z',
    message: 'Elevated token refresh latency in APAC.',
  },
  {
    id: 'svc-storage',
    name: 'Storage',
    category: 'storage',
    status: 'healthy',
    latencyMs: 65,
    uptimePercent: 99.99,
    lastCheckedAt: '2026-07-14T07:55:00Z',
    message: 'Object storage regions available.',
  },
  {
    id: 'svc-api',
    name: 'API Gateway',
    category: 'api',
    status: 'healthy',
    latencyMs: 88,
    uptimePercent: 99.92,
    lastCheckedAt: '2026-07-14T07:55:00Z',
    message: 'p95 within SLO.',
  },
  {
    id: 'svc-worker',
    name: 'Background Workers',
    category: 'worker',
    status: 'healthy',
    latencyMs: 0,
    uptimePercent: 99.9,
    lastCheckedAt: '2026-07-14T07:55:00Z',
    message: 'Queues draining within target.',
  },
];

export const MOCK_HEALTH_SCORE: HealthScoreSnapshot = {
  score: 96,
  status: 'healthy',
  healthyCount: 5,
  degradedCount: 1,
  downCount: 0,
  updatedAt: '2026-07-14T07:55:00Z',
};

export const MOCK_AUDIT_LOGS: readonly AuditLogRecord[] = [
  {
    id: 'aud-1',
    timestamp: '2026-07-14T07:40:00Z',
    actorName: 'Alex Rivera',
    actorEmail: 'alex@mypropertyasset.com',
    action: 'settings.update',
    category: 'settings',
    resource: 'platform.settings.security',
    ipAddress: '103.21.244.12',
    outcome: 'success',
    summary: 'Updated password policy minimum length to 12.',
    metadata: { field: 'passwordPolicy.minLength', from: '10', to: '12' },
  },
  {
    id: 'aud-2',
    timestamp: '2026-07-14T06:12:00Z',
    actorName: 'Jordan Lee',
    actorEmail: 'jordan@horizon.builders',
    action: 'organization.member.invite',
    category: 'organization',
    resource: 'org-horizon',
    organizationName: 'Horizon Builders',
    ipAddress: '49.36.18.90',
    outcome: 'success',
    summary: 'Invited sam.patel@horizon.builders as builder-org-member.',
  },
  {
    id: 'aud-3',
    timestamp: '2026-07-14T05:01:00Z',
    actorName: 'System',
    actorEmail: 'system@mypropertyasset.com',
    action: 'billing.invoice.past_due',
    category: 'billing',
    resource: 'inv-1002',
    organizationName: 'Apex Developments',
    builderName: 'Apex Developments Ltd',
    ipAddress: '—',
    outcome: 'failure',
    summary: 'Invoice INV-2026-1002 marked past due after payment failure.',
  },
  {
    id: 'aud-4',
    timestamp: '2026-07-13T22:18:00Z',
    actorName: 'Unknown',
    actorEmail: 'unknown@mail.test',
    action: 'auth.login',
    category: 'auth',
    resource: 'portal:super-admin',
    ipAddress: '185.220.101.4',
    outcome: 'denied',
    summary: 'Failed login attempt for super-admin portal.',
    metadata: { reason: 'invalid_credentials' },
  },
  {
    id: 'aud-5',
    timestamp: '2026-07-13T18:45:00Z',
    actorName: 'Priya Sharma',
    actorEmail: 'priya@mypropertyasset.com',
    action: 'builder.activate',
    category: 'builder',
    resource: 'builder-horizon',
    builderName: 'Horizon Builders Pvt Ltd',
    organizationName: 'Horizon Builders',
    ipAddress: '103.21.244.12',
    outcome: 'success',
    summary: 'Activated builder onboarding for Horizon Builders.',
  },
  {
    id: 'aud-6',
    timestamp: '2026-07-13T14:02:00Z',
    actorName: 'Alex Rivera',
    actorEmail: 'alex@mypropertyasset.com',
    action: 'branding.publish',
    category: 'system',
    resource: 'brand-platform',
    ipAddress: '103.21.244.12',
    outcome: 'success',
    summary: 'Published platform brand kit updates.',
  },
];

export const MOCK_USER_ACTIVITY: readonly OpsUserActivityRecord[] = [
  {
    id: 'act-1',
    timestamp: '2026-07-14T07:50:00Z',
    userName: 'Alex Rivera',
    email: 'alex@mypropertyasset.com',
    type: 'login',
    detail: 'Signed in to Super Admin portal',
    location: 'Bengaluru, IN',
  },
  {
    id: 'act-2',
    timestamp: '2026-07-14T06:55:00Z',
    userName: 'Unknown',
    email: 'unknown@mail.test',
    type: 'failed_login',
    detail: 'Failed MFA challenge — 3 consecutive attempts',
    location: 'Frankfurt, DE',
  },
  {
    id: 'act-3',
    timestamp: '2026-07-14T06:20:00Z',
    userName: 'Jordan Lee',
    email: 'jordan@horizon.builders',
    type: 'session',
    detail: 'Active session on Builder Portal (desktop)',
    organizationName: 'Horizon Builders',
    location: 'Mumbai, IN',
  },
  {
    id: 'act-4',
    timestamp: '2026-07-14T05:30:00Z',
    userName: 'Sam Patel',
    email: 'sam@apex.dev',
    type: 'security',
    detail: 'Password reset requested',
    organizationName: 'Apex Developments',
    location: 'Mumbai, IN',
  },
  {
    id: 'act-5',
    timestamp: '2026-07-13T21:10:00Z',
    userName: 'Priya Sharma',
    email: 'priya@mypropertyasset.com',
    type: 'org',
    detail: 'Updated Skyline Residences tenancy status to active',
    organizationName: 'Skyline Residences',
  },
  {
    id: 'act-6',
    timestamp: '2026-07-13T16:40:00Z',
    userName: 'Alex Rivera',
    email: 'alex@mypropertyasset.com',
    type: 'builder',
    detail: 'Reviewed Apex Developments onboarding checklist',
    organizationName: 'Apex Developments',
  },
];

const series = (base: number, variance: number): { label: string; value: number }[] =>
  ['00', '04', '08', '12', '16', '20', '24'].map((h, i) => ({
    label: `${h}:00`,
    value: Math.max(0, Math.round(base + Math.sin(i) * variance + i * 2)),
  }));

export const MOCK_METRICS: readonly MonitoringMetric[] = [
  {
    id: 'm-resp',
    label: 'Avg response time',
    value: 148,
    unit: 'ms',
    trend: 'down',
    deltaPercent: -6.2,
    series: series(150, 40),
  },
  {
    id: 'm-err',
    label: 'Error rate',
    value: 0.42,
    unit: '%',
    trend: 'up',
    deltaPercent: 12,
    series: series(0.3, 0.2).map((p) => ({ ...p, value: +(p.value / 100).toFixed(2) })),
  },
  {
    id: 'm-req',
    label: 'Requests / min',
    value: 1840,
    unit: 'rpm',
    trend: 'up',
    deltaPercent: 4.1,
    series: series(1600, 200),
  },
  {
    id: 'm-cpu',
    label: 'CPU utilization',
    value: 58,
    unit: '%',
    trend: 'flat',
    deltaPercent: 0.4,
    series: series(55, 8),
  },
];

export const MOCK_QUEUES: readonly QueueJobStatus[] = [
  {
    id: 'q-email',
    name: 'Email dispatch',
    pending: 12,
    processing: 3,
    failed: 0,
    status: 'healthy',
  },
  {
    id: 'q-docs',
    name: 'Document processing',
    pending: 4,
    processing: 1,
    failed: 1,
    status: 'degraded',
  },
  {
    id: 'q-webhooks',
    name: 'Outbound webhooks',
    pending: 0,
    processing: 0,
    failed: 0,
    status: 'healthy',
  },
];

export const MOCK_ALERTS: readonly OpsAlertRecord[] = [
  {
    id: 'al-1',
    severity: 'warning',
    title: 'Auth latency elevated',
    message: 'Token refresh p95 above 200ms in APAC for 25 minutes.',
    source: 'Authentication',
    createdAt: '2026-07-14T07:30:00Z',
    acknowledged: false,
  },
  {
    id: 'al-2',
    severity: 'critical',
    title: 'Payment webhook failures',
    message: 'Billing webhook retries exhausted for Apex Developments.',
    source: 'Billing',
    createdAt: '2026-07-14T04:15:00Z',
    acknowledged: false,
    organizationName: 'Apex Developments',
  },
  {
    id: 'al-3',
    severity: 'info',
    title: 'Scheduled maintenance window',
    message: 'Storage region IN-SOUTH maintenance planned for 20 Jul 02:00 IST.',
    source: 'Platform',
    createdAt: '2026-07-13T12:00:00Z',
    acknowledged: true,
    acknowledgedAt: '2026-07-13T12:30:00Z',
  },
  {
    id: 'al-4',
    severity: 'warning',
    title: 'Document queue backlog',
    message: 'Document processing queue has 1 failed job requiring review.',
    source: 'Workers',
    createdAt: '2026-07-14T07:10:00Z',
    acknowledged: false,
  },
];

export const MOCK_INCIDENTS: readonly IncidentRecord[] = [
  {
    id: 'inc-1',
    title: 'Auth latency degradation',
    severity: 'warning',
    status: 'monitoring',
    startedAt: '2026-07-14T07:20:00Z',
    updatedAt: '2026-07-14T07:50:00Z',
    summary: 'Investigating elevated refresh latency; traffic shifted to warm cache.',
  },
  {
    id: 'inc-2',
    title: 'Billing webhook intermittency',
    severity: 'critical',
    status: 'identified',
    startedAt: '2026-07-14T04:00:00Z',
    updatedAt: '2026-07-14T06:00:00Z',
    summary: 'Provider timeout identified; retries queued for affected tenants.',
  },
];

export const MOCK_TIMELINE: readonly TimelineEvent[] = [
  {
    id: 'tl-1',
    timestamp: '2026-07-14T07:50:00Z',
    title: 'Health check passed',
    description: '5/6 services healthy; auth degraded.',
    kind: 'health',
    severity: 'warning',
  },
  {
    id: 'tl-2',
    timestamp: '2026-07-14T07:40:00Z',
    title: 'Security settings updated',
    description: 'Password policy changed by Alex Rivera.',
    kind: 'audit',
  },
  {
    id: 'tl-3',
    timestamp: '2026-07-14T07:30:00Z',
    title: 'Alert opened',
    description: 'Auth latency elevated in APAC.',
    kind: 'alert',
    severity: 'warning',
  },
  {
    id: 'tl-4',
    timestamp: '2026-07-13T12:00:00Z',
    title: 'Maintenance notice published',
    description: 'Storage region maintenance window announced.',
    kind: 'maintenance',
    severity: 'info',
  },
];

export const TELEMETRY_PROVIDERS: readonly TelemetryProviderPlaceholder[] = [
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error tracking and release health.',
    status: 'planned',
    icon: 'pi pi-exclamation-circle',
  },
  {
    id: 'app-insights',
    name: 'Application Insights',
    description: 'Azure APM and telemetry.',
    status: 'planned',
    icon: 'pi pi-cloud',
  },
  {
    id: 'ga',
    name: 'Google Analytics',
    description: 'Product analytics signals.',
    status: 'coming_soon',
    icon: 'pi pi-chart-pie',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'Metrics dashboards and alerting.',
    status: 'coming_soon',
    icon: 'pi pi-chart-bar',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    description: 'Full-stack observability.',
    status: 'coming_soon',
    icon: 'pi pi-eye',
  },
  {
    id: 'otel',
    name: 'OpenTelemetry',
    description: 'Vendor-neutral traces and metrics.',
    status: 'planned',
    icon: 'pi pi-share-alt',
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    description: 'Time-series metrics store.',
    status: 'coming_soon',
    icon: 'pi pi-database',
  },
  {
    id: 'cloudwatch',
    name: 'CloudWatch',
    description: 'AWS logs and infrastructure metrics.',
    status: 'enterprise_only',
    icon: 'pi pi-server',
  },
];

export const AUDIT_CATEGORIES: readonly { id: AuditLogRecord['category'] | 'all'; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'auth', label: 'Auth' },
  { id: 'organization', label: 'Organization' },
  { id: 'builder', label: 'Builder' },
  { id: 'billing', label: 'Billing' },
  { id: 'settings', label: 'Settings' },
  { id: 'security', label: 'Security' },
  { id: 'system', label: 'System' },
  { id: 'user', label: 'User' },
];

export function formatOpsDate(iso: string): string {
  try {
    return new Intl.DateTimeFormat('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(new Date(iso));
  } catch {
    return iso;
  }
}
