import {
  BuilderActivityRecord,
  BuilderAdminRecord,
  BuilderAuditRecord,
  BuilderContactRecord,
  BuilderSavedView,
  BuilderStatusHistoryRecord,
  BuilderTableColumn,
} from '../models/builder-admin.model';

export const BUILDER_TABLE_COLUMNS: readonly BuilderTableColumn[] = [
  { id: 'companyName', label: 'Builder', sortable: true, defaultVisible: true },
  { id: 'status', label: 'Status', sortable: true, defaultVisible: true },
  { id: 'region', label: 'Region', sortable: true, defaultVisible: true },
  { id: 'plan', label: 'Plan', sortable: true, defaultVisible: true },
  { id: 'organizationName', label: 'Organization', sortable: true, defaultVisible: true },
  { id: 'projectCount', label: 'Projects', sortable: true, defaultVisible: false },
  { id: 'unitCount', label: 'Units', sortable: true, defaultVisible: false },
  { id: 'primaryContactName', label: 'Primary contact', sortable: true, defaultVisible: false },
  { id: 'createdAt', label: 'Registered', sortable: true, defaultVisible: false },
];

export const BUILDER_SAVED_VIEWS: readonly BuilderSavedView[] = [
  { id: 'all', name: 'All builders', statusFilter: 'all', regionFilter: '', isDefault: true },
  { id: 'active', name: 'Active builders', statusFilter: 'active', regionFilter: '' },
  { id: 'pending', name: 'Pending onboarding', statusFilter: 'pending', regionFilter: '' },
  { id: 'archived', name: 'Archived', statusFilter: 'archived', regionFilter: '' },
];

export const BUILDER_SORT_OPTIONS = [
  { label: 'Name A–Z', value: 'companyName:asc' },
  { label: 'Name Z–A', value: 'companyName:desc' },
  { label: 'Newest', value: 'createdAt:desc' },
  { label: 'Most projects', value: 'projectCount:desc' },
] as const;

const addr = (street: string, city: string, state: string, postal: string, country: string) => ({
  street,
  city,
  state,
  postalCode: postal,
  country,
});

export const MOCK_BUILDERS: readonly BuilderAdminRecord[] = [
  {
    id: 'bld-001',
    companyName: 'Apex Developments',
    tradingName: 'Apex',
    status: 'active',
    primaryColor: '#1B4D89',
    secondaryColor: '#3B82F6',
    registrationNumber: 'REG-2024-8841',
    registeredAt: '2024-11-12',
    primaryContactName: 'Sarah Chen',
    primaryContactEmail: 'sarah.chen@apexdev.com',
    primaryContactPhone: '+1 415 555 0101',
    address: addr('1200 Market Street', 'San Francisco', 'CA', '94102', 'United States'),
    organizationId: 'org-001',
    organizationName: 'Apex Developments',
    region: 'North America',
    plan: 'Enterprise',
    projectCount: 18,
    unitCount: 420,
    ownerCount: 156,
    contactCount: 42,
    documentCount: 128,
    invitationCount: 3,
    whiteLabelEnabled: true,
    createdAt: '2024-11-12T10:00:00Z',
    updatedAt: '2026-07-08T14:22:00Z',
  },
  {
    id: 'bld-002',
    companyName: 'Sterling Construction Group',
    tradingName: 'Sterling',
    status: 'active',
    primaryColor: '#1E40AF',
    secondaryColor: '#60A5FA',
    registrationNumber: 'REG-2025-1204',
    registeredAt: '2025-04-05',
    primaryContactName: 'Patricia Okafor',
    primaryContactEmail: 'p.okafor@sterlingcg.com',
    primaryContactPhone: '+44 20 7946 0958',
    address: addr('45 Canary Wharf', 'London', 'England', 'E14 5AB', 'United Kingdom'),
    organizationId: 'org-010',
    organizationName: 'Sterling Construction Group',
    region: 'Europe',
    plan: 'Enterprise',
    projectCount: 31,
    unitCount: 890,
    ownerCount: 312,
    contactCount: 67,
    documentCount: 245,
    invitationCount: 5,
    whiteLabelEnabled: true,
    createdAt: '2025-04-05T10:00:00Z',
    updatedAt: '2026-07-11T08:45:00Z',
  },
  {
    id: 'bld-003',
    companyName: 'Summit Property Group',
    status: 'pending',
    primaryColor: '#7C3AED',
    secondaryColor: '#A78BFA',
    registrationNumber: 'REG-2026-3301',
    registeredAt: '2026-07-09',
    primaryContactName: 'Elena Vasquez',
    primaryContactEmail: 'elena@summitpg.com',
    address: addr('88 Congress Ave', 'Austin', 'TX', '78701', 'United States'),
    organizationId: 'org-003',
    organizationName: 'Summit Property Group',
    region: 'North America',
    plan: 'Growth',
    projectCount: 0,
    unitCount: 0,
    ownerCount: 0,
    contactCount: 3,
    documentCount: 2,
    invitationCount: 1,
    whiteLabelEnabled: false,
    createdAt: '2026-07-09T16:45:00Z',
    updatedAt: '2026-07-10T11:00:00Z',
  },
  {
    id: 'bld-004',
    companyName: 'Coastal Living Builders',
    tradingName: 'Coastal',
    status: 'inactive',
    primaryColor: '#0891B2',
    secondaryColor: '#22D3EE',
    registrationNumber: 'REG-2023-5520',
    registeredAt: '2023-06-14',
    primaryContactName: 'Anna Park',
    primaryContactEmail: 'anna@coastalliving.com',
    address: addr('200 Ocean Drive', 'Miami', 'FL', '33139', 'United States'),
    organizationId: 'org-005',
    organizationName: 'Coastal Living Builders',
    region: 'North America',
    plan: 'Professional',
    projectCount: 4,
    unitCount: 96,
    ownerCount: 28,
    contactCount: 15,
    documentCount: 34,
    invitationCount: 0,
    whiteLabelEnabled: true,
    createdAt: '2025-06-14T09:00:00Z',
    updatedAt: '2026-05-12T08:00:00Z',
  },
  {
    id: 'bld-005',
    companyName: 'Pacific Ridge Homes',
    status: 'active',
    primaryColor: '#059669',
    secondaryColor: '#34D399',
    registrationNumber: 'REG-2025-7782',
    registeredAt: '2025-09-22',
    primaryContactName: 'Kenji Watanabe',
    primaryContactEmail: 'k.watanabe@pacificridge.jp',
    address: addr('2-1 Marunouchi', 'Tokyo', 'Tokyo', '100-0005', 'Japan'),
    organizationId: 'org-008',
    organizationName: 'Pacific Asset Holdings',
    region: 'Asia Pacific',
    plan: 'Enterprise',
    projectCount: 11,
    unitCount: 280,
    ownerCount: 94,
    contactCount: 34,
    documentCount: 87,
    invitationCount: 2,
    whiteLabelEnabled: true,
    createdAt: '2025-09-22T07:00:00Z',
    updatedAt: '2026-07-07T13:20:00Z',
  },
  {
    id: 'bld-006',
    companyName: 'Legacy Homes Inc.',
    status: 'archived',
    primaryColor: '#6B7280',
    secondaryColor: '#9CA3AF',
    registrationNumber: 'REG-2022-1102',
    registeredAt: '2022-03-10',
    primaryContactName: 'Robert Hayes',
    primaryContactEmail: 'r.hayes@legacyhomes.com',
    address: addr('500 Industrial Blvd', 'Detroit', 'MI', '48201', 'United States'),
    organizationId: 'org-007',
    organizationName: 'Legacy Homes Inc.',
    region: 'North America',
    plan: 'Growth',
    projectCount: 2,
    unitCount: 24,
    ownerCount: 8,
    contactCount: 0,
    documentCount: 12,
    invitationCount: 0,
    whiteLabelEnabled: false,
    createdAt: '2024-03-10T11:00:00Z',
    updatedAt: '2026-02-28T16:00:00Z',
  },
];

export const MOCK_BUILDER_CONTACTS: readonly BuilderContactRecord[] = [
  { id: 'bc-001', builderId: 'bld-001', name: 'Sarah Chen', email: 'sarah.chen@apexdev.com', phone: '+1 415 555 0101', role: 'builder-org-owner', isPrimary: true, status: 'active' },
  { id: 'bc-002', builderId: 'bld-001', name: 'Tom Bradley', email: 'tom.b@apexdev.com', role: 'builder-org-admin', status: 'active' },
  { id: 'bc-003', builderId: 'bld-001', name: 'Alex Rivera', email: 'alex.r@apexdev.com', role: 'builder-org-member', status: 'invited', invitedAt: '2026-07-08T10:00:00Z' },
  { id: 'bc-004', builderId: 'bld-002', name: 'Patricia Okafor', email: 'p.okafor@sterlingcg.com', role: 'builder-org-owner', isPrimary: true, status: 'active' },
  { id: 'bc-005', builderId: 'bld-003', name: 'Elena Vasquez', email: 'elena@summitpg.com', role: 'builder-org-owner', isPrimary: true, status: 'active' },
];

export const MOCK_BUILDER_ACTIVITIES: readonly BuilderActivityRecord[] = [
  { id: 'ba-001', builderId: 'bld-001', title: 'Builder approved', description: 'Onboarding review completed.', timestamp: '2024-11-12T10:00:00Z', type: 'status' },
  { id: 'ba-002', builderId: 'bld-001', title: 'Branding configured', description: 'Primary and secondary colors set.', timestamp: '2024-12-01T14:30:00Z', type: 'branding' },
  { id: 'ba-003', builderId: 'bld-003', title: 'Registration submitted', description: 'Pending Super Admin review.', timestamp: '2026-07-09T16:45:00Z', type: 'registration' },
  { id: 'ba-004', builderId: 'bld-006', title: 'Builder archived', description: 'Tenant offboarded from platform.', timestamp: '2026-02-28T16:00:00Z', type: 'status' },
];

export const MOCK_BUILDER_STATUS_HISTORY: readonly BuilderStatusHistoryRecord[] = [
  { id: 'bsh-001', builderId: 'bld-001', status: 'pending', changedAt: '2024-11-10T09:00:00Z', changedBy: 'System', reason: 'Registration submitted' },
  { id: 'bsh-002', builderId: 'bld-001', status: 'active', changedAt: '2024-11-12T10:00:00Z', changedBy: 'Super Admin', reason: 'Onboarding approved' },
  { id: 'bsh-003', builderId: 'bld-006', status: 'archived', changedAt: '2026-02-28T16:00:00Z', changedBy: 'Super Admin', reason: 'Builder offboarded' },
];

export const MOCK_BUILDER_AUDITS: readonly BuilderAuditRecord[] = [
  { id: 'bad-001', builderId: 'bld-001', action: 'Profile updated', actor: 'Super Admin', timestamp: '2026-07-08T14:22:00Z', detail: 'Contact phone updated' },
  { id: 'bad-002', builderId: 'bld-003', action: 'Registration created', actor: 'System', timestamp: '2026-07-09T16:45:00Z', detail: 'Pending onboarding record' },
];
