import { Building } from '../models/building.model';

export const SEED_BUILDER_BUILDINGS: readonly Building[] = [
  {
    id: 'bld-001',
    projectId: 'proj-001',
    organizationId: 'org-builder-demo',
    name: 'Tower A',
    code: 'HZT-A',
    towerName: 'Tower A',
    blockName: 'Block A',
    displayOrder: 1,
    floorsCount: 28,
    unitsCount: 112,
    status: 'construction',
    description: 'Primary residential tower facing the boulevard.',
    addressLine: 'Plot 14, Sector 12 — Tower A',
    archived: false,
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2026-07-12T10:00:00Z',
  },
  {
    id: 'bld-002',
    projectId: 'proj-001',
    organizationId: 'org-builder-demo',
    name: 'Tower B',
    code: 'HZT-B',
    towerName: 'Tower B',
    blockName: 'Block B',
    displayOrder: 2,
    floorsCount: 28,
    unitsCount: 112,
    status: 'construction',
    description: 'Secondary twin tower with podium amenities.',
    addressLine: 'Plot 14, Sector 12 — Tower B',
    archived: false,
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2026-07-11T10:00:00Z',
  },
  {
    id: 'bld-003',
    projectId: 'proj-002',
    organizationId: 'org-builder-demo',
    name: 'Skyline Block 1',
    code: 'SKR-1',
    towerName: 'Block 1',
    displayOrder: 1,
    floorsCount: 18,
    unitsCount: 80,
    status: 'completed',
    description: 'Near-completion mid-rise block.',
    archived: false,
    createdAt: '2024-01-01T09:00:00Z',
    updatedAt: '2026-07-10T08:00:00Z',
  },
  {
    id: 'bld-004',
    projectId: 'proj-003',
    organizationId: 'org-builder-demo',
    name: 'Meadow East',
    code: 'MDH-E',
    towerName: 'East Wing',
    blockName: 'Phase 1',
    displayOrder: 1,
    floorsCount: 22,
    unitsCount: 160,
    status: 'construction',
    description: 'East wing of the mixed township.',
    archived: false,
    createdAt: '2024-08-01T09:00:00Z',
    updatedAt: '2026-07-09T14:00:00Z',
  },
  {
    id: 'bld-005',
    projectId: 'proj-007',
    organizationId: 'org-builder-demo',
    name: 'Cedar Tower',
    code: 'CBP-T1',
    towerName: 'Cedar Tower',
    displayOrder: 1,
    floorsCount: 16,
    unitsCount: 96,
    status: 'planning',
    description: 'Commercial office tower.',
    archived: false,
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2026-07-06T15:00:00Z',
  },
  {
    id: 'bld-006',
    projectId: 'proj-001',
    organizationId: 'org-builder-demo',
    name: 'Podium Retail',
    code: 'HZT-P',
    blockName: 'Podium',
    displayOrder: 3,
    floorsCount: 3,
    unitsCount: 24,
    status: 'archived',
    description: 'Archived early podium scheme.',
    archived: true,
    createdAt: '2025-02-01T09:00:00Z',
    updatedAt: '2025-06-01T09:00:00Z',
  },
];
