export {
  AUTHENTICATION_NAVIGATION,
  BLANK_NAVIGATION,
  BUILDER_PORTAL_NAVIGATION,
  NAVIGATION_CONFIGURATIONS,
  NAVIGATION_METADATA,
  PARTNER_PORTAL_NAVIGATION,
  PUBLIC_WEBSITE_NAVIGATION,
  SUPER_ADMIN_NAVIGATION,
  TENANT_PORTAL_NAVIGATION,
} from './navigation.config';
