import {
  OrganizationActivityRecord,
  OrganizationAdminRecord,
  OrganizationAuditRecord,
  OrganizationMemberRecord,
  OrganizationSavedView,
  OrganizationStatusHistoryRecord,
  OrganizationTableColumn,
} from '../models/organization-admin.model';

export const ORGANIZATION_TABLE_COLUMNS: readonly OrganizationTableColumn[] = [
  { id: 'name', label: 'Organization', sortable: true, defaultVisible: true },
  { id: 'type', label: 'Type', sortable: true, defaultVisible: true },
  { id: 'status', label: 'Status', sortable: true, defaultVisible: true },
  { id: 'region', label: 'Region', sortable: true, defaultVisible: true },
  { id: 'plan', label: 'Plan', sortable: true, defaultVisible: true },
  { id: 'memberCount', label: 'Members', sortable: true, defaultVisible: true },
  { id: 'subscriptionTier', label: 'Subscription', sortable: true, defaultVisible: false },
  { id: 'createdAt', label: 'Created', sortable: true, defaultVisible: false },
  { id: 'updatedAt', label: 'Updated', sortable: true, defaultVisible: false },
];

export const ORGANIZATION_SAVED_VIEWS: readonly OrganizationSavedView[] = [
  { id: 'all', name: 'All organizations', statusFilter: 'all', typeFilter: 'all', isDefault: true },
  { id: 'active-builders', name: 'Active builders', statusFilter: 'active', typeFilter: 'builder' },
  { id: 'pending', name: 'Pending onboarding', statusFilter: 'pending', typeFilter: 'all' },
  { id: 'archived', name: 'Archived', statusFilter: 'archived', typeFilter: 'all' },
];

export const ORGANIZATION_STATUS_OPTIONS = [
  { label: 'All statuses', value: 'all' },
  { label: 'Active', value: 'active' },
  { label: 'Inactive', value: 'inactive' },
  { label: 'Pending', value: 'pending' },
  { label: 'Archived', value: 'archived' },
] as const;

export const ORGANIZATION_TYPE_OPTIONS = [
  { label: 'All types', value: 'all' },
  { label: 'Builder', value: 'builder' },
  { label: 'Owner', value: 'owner' },
  { label: 'Partner', value: 'partner' },
  { label: 'Marketplace', value: 'marketplace' },
] as const;

export const ORGANIZATION_SORT_OPTIONS = [
  { label: 'Name A–Z', value: 'name:asc' },
  { label: 'Name Z–A', value: 'name:desc' },
  { label: 'Newest', value: 'createdAt:desc' },
  { label: 'Oldest', value: 'createdAt:asc' },
  { label: 'Most members', value: 'memberCount:desc' },
] as const;

export const MOCK_ORGANIZATIONS: readonly OrganizationAdminRecord[] = [
  {
    id: 'org-001',
    name: 'Apex Developments',
    shortName: 'Apex',
    type: 'builder',
    status: 'active',
    logoUrl: undefined,
    primaryColor: '#1B4D89',
    contactName: 'Sarah Chen',
    contactEmail: 'sarah.chen@apexdev.com',
    region: 'North America',
    plan: 'Enterprise',
    slug: 'apex-developments',
    description: 'Premium residential and mixed-use builder.',
    memberCount: 42,
    projectCount: 18,
    subscriptionTier: 'Enterprise',
    subscriptionStatus: 'active',
    whiteLabelEnabled: true,
    supportAccessEnabled: true,
    createdAt: '2025-11-12T10:00:00Z',
    updatedAt: '2026-07-08T14:22:00Z',
  },
  {
    id: 'org-002',
    name: 'Horizon Estates',
    shortName: 'Horizon',
    type: 'owner',
    status: 'active',
    primaryColor: '#2D6A4F',
    contactName: 'Michael Torres',
    contactEmail: 'm.torres@horizonestates.com',
    region: 'Europe',
    plan: 'Professional',
    slug: 'horizon-estates',
    description: 'Institutional property owner portfolio.',
    memberCount: 28,
    projectCount: 9,
    subscriptionTier: 'Professional',
    subscriptionStatus: 'active',
    whiteLabelEnabled: false,
    supportAccessEnabled: true,
    createdAt: '2025-12-03T08:30:00Z',
    updatedAt: '2026-07-05T09:15:00Z',
  },
  {
    id: 'org-003',
    name: 'Summit Property Group',
    shortName: 'Summit',
    type: 'builder',
    status: 'pending',
    primaryColor: '#7C3AED',
    contactName: 'Elena Vasquez',
    contactEmail: 'elena@summitpg.com',
    region: 'North America',
    plan: 'Growth',
    slug: 'summit-property-group',
    description: 'Evaluation-phase builder onboarding.',
    memberCount: 3,
    projectCount: 0,
    subscriptionTier: 'Trial',
    subscriptionStatus: 'trial',
    whiteLabelEnabled: false,
    supportAccessEnabled: false,
    createdAt: '2026-07-09T16:45:00Z',
    updatedAt: '2026-07-10T11:00:00Z',
  },
  {
    id: 'org-004',
    name: 'Meridian Capital Partners',
    type: 'owner',
    status: 'active',
    primaryColor: '#B45309',
    contactName: 'James Whitfield',
    contactEmail: 'j.whitfield@meridiancp.com',
    region: 'Asia Pacific',
    plan: 'Enterprise',
    slug: 'meridian-capital',
    memberCount: 56,
    projectCount: 22,
    subscriptionTier: 'Enterprise',
    subscriptionStatus: 'active',
    whiteLabelEnabled: true,
    supportAccessEnabled: true,
    createdAt: '2025-08-20T12:00:00Z',
    updatedAt: '2026-06-28T17:40:00Z',
  },
  {
    id: 'org-005',
    name: 'Coastal Living Builders',
    shortName: 'Coastal',
    type: 'builder',
    status: 'inactive',
    primaryColor: '#0891B2',
    contactName: 'Anna Park',
    contactEmail: 'anna@coastalliving.com',
    region: 'North America',
    plan: 'Professional',
    slug: 'coastal-living',
    memberCount: 15,
    projectCount: 4,
    subscriptionTier: 'Professional',
    subscriptionStatus: 'expired',
    whiteLabelEnabled: true,
    supportAccessEnabled: false,
    createdAt: '2025-06-14T09:00:00Z',
    updatedAt: '2026-05-12T08:00:00Z',
  },
  {
    id: 'org-006',
    name: 'Vertex Realty Partners',
    type: 'partner',
    status: 'active',
    primaryColor: '#DC2626',
    contactName: 'David Kim',
    contactEmail: 'david.kim@vertexrealty.com',
    region: 'Europe',
    plan: 'Partner',
    slug: 'vertex-realty',
    memberCount: 12,
    projectCount: 0,
    subscriptionTier: 'Partner',
    subscriptionStatus: 'active',
    whiteLabelEnabled: false,
    supportAccessEnabled: true,
    createdAt: '2026-01-18T14:00:00Z',
    updatedAt: '2026-07-01T10:30:00Z',
  },
  {
    id: 'org-007',
    name: 'Legacy Homes Inc.',
    type: 'builder',
    status: 'archived',
    primaryColor: '#6B7280',
    contactName: 'Robert Hayes',
    contactEmail: 'r.hayes@legacyhomes.com',
    region: 'North America',
    plan: 'Growth',
    slug: 'legacy-homes',
    memberCount: 0,
    projectCount: 2,
    subscriptionTier: 'Growth',
    subscriptionStatus: 'none',
    whiteLabelEnabled: false,
    supportAccessEnabled: false,
    createdAt: '2024-03-10T11:00:00Z',
    updatedAt: '2026-02-28T16:00:00Z',
  },
  {
    id: 'org-008',
    name: 'Pacific Asset Holdings',
    type: 'owner',
    status: 'active',
    primaryColor: '#059669',
    contactName: 'Lisa Nakamura',
    contactEmail: 'l.nakamura@pacificasset.com',
    region: 'Asia Pacific',
    plan: 'Enterprise',
    slug: 'pacific-asset',
    memberCount: 34,
    projectCount: 11,
    subscriptionTier: 'Enterprise',
    subscriptionStatus: 'active',
    whiteLabelEnabled: true,
    supportAccessEnabled: true,
    createdAt: '2025-09-22T07:00:00Z',
    updatedAt: '2026-07-07T13:20:00Z',
  },
  {
    id: 'org-009',
    name: 'UrbanNest Marketplace',
    type: 'marketplace',
    status: 'pending',
    primaryColor: '#9333EA',
    contactName: 'Chris Morgan',
    contactEmail: 'chris@urbannest.io',
    region: 'North America',
    plan: 'Marketplace',
    slug: 'urbannest',
    memberCount: 8,
    projectCount: 0,
    subscriptionTier: 'Trial',
    subscriptionStatus: 'trial',
    whiteLabelEnabled: false,
    supportAccessEnabled: false,
    createdAt: '2026-06-30T15:00:00Z',
    updatedAt: '2026-07-09T09:00:00Z',
  },
  {
    id: 'org-010',
    name: 'Sterling Construction Group',
    shortName: 'Sterling',
    type: 'builder',
    status: 'active',
    primaryColor: '#1E40AF',
    contactName: 'Patricia Okafor',
    contactEmail: 'p.okafor@sterlingcg.com',
    region: 'Europe',
    plan: 'Enterprise',
    slug: 'sterling-construction',
    memberCount: 67,
    projectCount: 31,
    subscriptionTier: 'Enterprise',
    subscriptionStatus: 'active',
    whiteLabelEnabled: true,
    supportAccessEnabled: true,
    createdAt: '2025-04-05T10:00:00Z',
    updatedAt: '2026-07-11T08:45:00Z',
  },
];

export const MOCK_ORGANIZATION_MEMBERS: readonly OrganizationMemberRecord[] = [
  { id: 'mem-001', organizationId: 'org-001', name: 'Sarah Chen', email: 'sarah.chen@apexdev.com', role: 'builder-org-owner', status: 'active', joinedAt: '2025-11-12T10:00:00Z' },
  { id: 'mem-002', organizationId: 'org-001', name: 'Tom Bradley', email: 'tom.b@apexdev.com', role: 'builder-org-admin', status: 'active', joinedAt: '2025-11-15T09:00:00Z' },
  { id: 'mem-003', organizationId: 'org-001', name: 'Nina Patel', email: 'nina.p@apexdev.com', role: 'builder-org-member', status: 'active', joinedAt: '2026-01-20T14:00:00Z' },
  { id: 'mem-004', organizationId: 'org-001', name: 'Alex Rivera', email: 'alex.r@apexdev.com', role: 'builder-org-member', status: 'invited', invitedAt: '2026-07-08T10:00:00Z' },
  { id: 'mem-005', organizationId: 'org-002', name: 'Michael Torres', email: 'm.torres@horizonestates.com', role: 'owner-org-owner', status: 'active', joinedAt: '2025-12-03T08:30:00Z' },
  { id: 'mem-006', organizationId: 'org-002', name: 'Sophie Laurent', email: 's.laurent@horizonestates.com', role: 'owner-web-user', status: 'active', joinedAt: '2026-02-10T11:00:00Z' },
  { id: 'mem-007', organizationId: 'org-003', name: 'Elena Vasquez', email: 'elena@summitpg.com', role: 'builder-org-owner', status: 'active', joinedAt: '2026-07-09T16:45:00Z' },
];

export const MOCK_ORGANIZATION_ACTIVITIES: readonly OrganizationActivityRecord[] = [
  { id: 'act-001', organizationId: 'org-001', title: 'Status changed to Active', description: 'Onboarding review completed.', timestamp: '2025-11-12T10:00:00Z', type: 'status' },
  { id: 'act-002', organizationId: 'org-001', title: 'Branding updated', description: 'Primary color and logo configured.', timestamp: '2025-12-01T14:30:00Z', type: 'branding' },
  { id: 'act-003', organizationId: 'org-001', title: 'Member invited', description: 'Alex Rivera invited as builder member.', timestamp: '2026-07-08T10:00:00Z', type: 'member' },
  { id: 'act-004', organizationId: 'org-003', title: 'Organization created', description: 'Entered evaluation onboarding.', timestamp: '2026-07-09T16:45:00Z', type: 'system' },
  { id: 'act-005', organizationId: 'org-007', title: 'Archived', description: 'Organization deactivated and archived.', timestamp: '2026-02-28T16:00:00Z', type: 'status' },
];

export const MOCK_ORGANIZATION_STATUS_HISTORY: readonly OrganizationStatusHistoryRecord[] = [
  { id: 'sh-001', organizationId: 'org-001', status: 'pending', changedAt: '2025-11-10T09:00:00Z', changedBy: 'System', reason: 'Registration submitted' },
  { id: 'sh-002', organizationId: 'org-001', status: 'active', changedAt: '2025-11-12T10:00:00Z', changedBy: 'Super Admin', reason: 'Onboarding approved' },
  { id: 'sh-003', organizationId: 'org-007', status: 'inactive', changedAt: '2026-01-15T12:00:00Z', changedBy: 'Super Admin', reason: 'Subscription lapsed' },
  { id: 'sh-004', organizationId: 'org-007', status: 'archived', changedAt: '2026-02-28T16:00:00Z', changedBy: 'Super Admin', reason: 'Tenant offboarded' },
];

export const MOCK_ORGANIZATION_AUDITS: readonly OrganizationAuditRecord[] = [
  { id: 'aud-001', organizationId: 'org-001', action: 'Organization updated', actor: 'Super Admin', timestamp: '2026-07-08T14:22:00Z', detail: 'Contact email updated' },
  { id: 'aud-002', organizationId: 'org-001', action: 'Branding changed', actor: 'Sarah Chen', timestamp: '2025-12-01T14:30:00Z', detail: 'Primary color set to #1B4D89' },
  { id: 'aud-003', organizationId: 'org-003', action: 'Organization created', actor: 'System', timestamp: '2026-07-09T16:45:00Z', detail: 'Pending onboarding record' },
];
