import { PlatformRole } from '@core/rbac/models/permission.model';

import { InvitationAdminRecord, InvitationTimelineEvent } from '../models/invitation-admin.model';
import { PermissionCategory } from '../models/permission-admin.model';
import {
  UserActivityRecord,
  UserAdminRecord,
  UserAuditRecord,
  UserSavedView,
  UserStatusHistoryRecord,
  UserTableColumn,
} from '../models/user-admin.model';

export const USER_TABLE_COLUMNS: readonly UserTableColumn[] = [
  { id: 'displayName', label: 'User', sortable: true, defaultVisible: true },
  { id: 'email', label: 'Email', sortable: true, defaultVisible: true },
  { id: 'status', label: 'Status', sortable: false, defaultVisible: true },
  { id: 'primaryRole', label: 'Role', sortable: true, defaultVisible: true },
  { id: 'organizationName', label: 'Organization', sortable: true, defaultVisible: true },
  { id: 'builderName', label: 'Builder', sortable: false, defaultVisible: false },
  { id: 'lastLoginAt', label: 'Last login', sortable: true, defaultVisible: true },
  { id: 'mfaEnabled', label: 'MFA', sortable: false, defaultVisible: false },
  { id: 'createdAt', label: 'Created', sortable: true, defaultVisible: false },
];

export const USER_SAVED_VIEWS: readonly UserSavedView[] = [
  { id: 'all', name: 'All users', statusFilter: 'all', roleFilter: 'all', isDefault: true },
  { id: 'active', name: 'Active users', statusFilter: 'active', roleFilter: 'all' },
  { id: 'pending', name: 'Pending activation', statusFilter: 'pending', roleFilter: 'all' },
  { id: 'admins', name: 'Administrators', statusFilter: 'all', roleFilter: 'super-admin' },
  { id: 'suspended', name: 'Suspended', statusFilter: 'suspended', roleFilter: 'all' },
];

export const USER_SORT_OPTIONS = [
  { label: 'Name A–Z', value: 'displayName:asc' },
  { label: 'Name Z–A', value: 'displayName:desc' },
  { label: 'Email A–Z', value: 'email:asc' },
  { label: 'Recently active', value: 'lastLoginAt:desc' },
  { label: 'Recently created', value: 'createdAt:desc' },
];

export const RESOURCE_LABELS: Record<string, string> = {
  'id-01-marketing-leads': 'Marketing & Leads',
  'id-02-builder-onboarding': 'Builder Onboarding',
  'id-03-organization-tenancy': 'Organization & Tenancy',
  'id-04-white-label-branding': 'White-label Branding',
  'id-05-subscription-commercial': 'Subscription & Commercial',
  'id-06-platform-operations': 'Platform Operations',
  'id-07-project-unit': 'Projects & Units',
  'id-08-owner-assignment-prospect': 'Owner Assignment',
  'id-09-handover-document': 'Handover & Documents',
  'id-10-invitation': 'Invitations',
  'id-11-notification': 'Notifications',
  'id-12-reporting-analytics': 'Reporting & Analytics',
  'id-13-owner-financial-property': 'Owner Financial & Property',
  'id-14-user-identity-access': 'User Identity & Access',
  'id-15-future-tenant': 'Future Tenant',
  portal: 'Portal Access',
};

export const PERMISSION_CATEGORIES: readonly PermissionCategory[] = [
  {
    id: 'platform',
    label: 'Platform Governance',
    description: 'Core platform administration and operations',
    resources: ['id-06-platform-operations', 'id-14-user-identity-access', 'portal'],
  },
  {
    id: 'tenancy',
    label: 'Tenancy & Organizations',
    description: 'Multi-tenant organization management',
    resources: ['id-03-organization-tenancy', 'id-02-builder-onboarding', 'id-04-white-label-branding'],
  },
  {
    id: 'commercial',
    label: 'Commercial & Growth',
    description: 'Subscriptions, marketing, and commercial operations',
    resources: ['id-01-marketing-leads', 'id-05-subscription-commercial'],
  },
  {
    id: 'operations',
    label: 'Property Operations',
    description: 'Projects, units, owners, and handover workflows',
    resources: ['id-07-project-unit', 'id-08-owner-assignment-prospect', 'id-09-handover-document', 'id-13-owner-financial-property'],
  },
  {
    id: 'collaboration',
    label: 'Collaboration & Engagement',
    description: 'Invitations, notifications, and user engagement',
    resources: ['id-10-invitation', 'id-11-notification'],
  },
  {
    id: 'insights',
    label: 'Insights & Analytics',
    description: 'Reporting and platform intelligence',
    resources: ['id-12-reporting-analytics', 'id-15-future-tenant'],
  },
];

export const ROLE_DESCRIPTIONS: Partial<Record<PlatformRole, string>> = {
  'super-admin': 'Full platform administration across all tenants and system configuration.',
  'builder-org-owner': 'Primary builder organization owner with full org governance.',
  'builder-org-admin': 'Builder organization administrator with operational access.',
  'builder-org-member': 'Builder team member with project and unit contribution access.',
  'owner-org-owner': 'Property owner organization lead with portfolio governance.',
  'owner-web-user': 'Owner portal user with property and financial visibility.',
  'tenant-portal-user': 'Tenant portal access for lease and service interactions.',
  'support-user': 'Platform support operator with delegated cross-tenant access.',
  'public-visitor': 'Unauthenticated public website visitor with limited read access.',
};

export const MOCK_USERS: readonly UserAdminRecord[] = [
  {
    id: 'usr-001',
    email: 'sarah.chen@mypropertyasset.com',
    displayName: 'Sarah Chen',
    firstName: 'Sarah',
    lastName: 'Chen',
    status: 'active',
    primaryRole: 'super-admin',
    memberships: [{ organizationId: 'org-platform', organizationName: 'MyPropertyAsset Platform', organizationType: 'platform', role: 'super-admin', isPrimary: true }],
    organizationId: 'org-platform',
    organizationName: 'MyPropertyAsset Platform',
    lastLoginAt: '2026-07-13T08:30:00Z',
    lastActiveAt: '2026-07-13T10:15:00Z',
    mfaEnabled: true,
    emailVerified: true,
    sessionCount: 2,
    permissionCount: 16,
    invitationStatus: 'accepted',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2026-07-13T10:15:00Z',
  },
  {
    id: 'usr-002',
    email: 'marcus.rivera@horizonbuilders.com',
    displayName: 'Marcus Rivera',
    firstName: 'Marcus',
    lastName: 'Rivera',
    status: 'active',
    primaryRole: 'builder-org-owner',
    memberships: [{ organizationId: 'org-001', organizationName: 'Horizon Builders', organizationType: 'builder', role: 'builder-org-owner', isPrimary: true }],
    organizationId: 'org-001',
    organizationName: 'Horizon Builders',
    builderId: 'bld-001',
    builderName: 'Horizon Builders',
    lastLoginAt: '2026-07-12T14:22:00Z',
    lastActiveAt: '2026-07-12T16:45:00Z',
    mfaEnabled: true,
    emailVerified: true,
    sessionCount: 1,
    permissionCount: 12,
    invitationStatus: 'accepted',
    createdAt: '2024-03-20T00:00:00Z',
    updatedAt: '2026-07-12T16:45:00Z',
  },
  {
    id: 'usr-003',
    email: 'priya.sharma@horizonbuilders.com',
    displayName: 'Priya Sharma',
    firstName: 'Priya',
    lastName: 'Sharma',
    status: 'active',
    primaryRole: 'builder-org-admin',
    memberships: [{ organizationId: 'org-001', organizationName: 'Horizon Builders', organizationType: 'builder', role: 'builder-org-admin', isPrimary: true }],
    organizationId: 'org-001',
    organizationName: 'Horizon Builders',
    builderId: 'bld-001',
    builderName: 'Horizon Builders',
    lastLoginAt: '2026-07-11T09:10:00Z',
    mfaEnabled: false,
    emailVerified: true,
    sessionCount: 1,
    permissionCount: 10,
    invitationStatus: 'accepted',
    createdAt: '2024-06-10T00:00:00Z',
    updatedAt: '2026-07-11T09:10:00Z',
  },
  {
    id: 'usr-004',
    email: 'james.okonkwo@skylinedevelopments.com',
    displayName: 'James Okonkwo',
    firstName: 'James',
    lastName: 'Okonkwo',
    status: 'active',
    primaryRole: 'builder-org-owner',
    memberships: [{ organizationId: 'org-002', organizationName: 'Skyline Developments', organizationType: 'builder', role: 'builder-org-owner', isPrimary: true }],
    organizationId: 'org-002',
    organizationName: 'Skyline Developments',
    builderId: 'bld-002',
    builderName: 'Skyline Developments',
    lastLoginAt: '2026-07-10T11:00:00Z',
    mfaEnabled: true,
    emailVerified: true,
    sessionCount: 1,
    permissionCount: 12,
    invitationStatus: 'accepted',
    createdAt: '2024-04-05T00:00:00Z',
    updatedAt: '2026-07-10T11:00:00Z',
  },
  {
    id: 'usr-005',
    email: 'elena.vasquez@capitalowners.com',
    displayName: 'Elena Vasquez',
    firstName: 'Elena',
    lastName: 'Vasquez',
    status: 'active',
    primaryRole: 'owner-org-owner',
    memberships: [{ organizationId: 'org-003', organizationName: 'Capital Owners Group', organizationType: 'owner', role: 'owner-org-owner', isPrimary: true }],
    organizationId: 'org-003',
    organizationName: 'Capital Owners Group',
    lastLoginAt: '2026-07-09T07:30:00Z',
    mfaEnabled: true,
    emailVerified: true,
    sessionCount: 1,
    permissionCount: 6,
    invitationStatus: 'accepted',
    createdAt: '2024-08-12T00:00:00Z',
    updatedAt: '2026-07-09T07:30:00Z',
  },
  {
    id: 'usr-006',
    email: 'david.kim@horizonbuilders.com',
    displayName: 'David Kim',
    firstName: 'David',
    lastName: 'Kim',
    status: 'pending',
    primaryRole: 'builder-org-member',
    memberships: [{ organizationId: 'org-001', organizationName: 'Horizon Builders', organizationType: 'builder', role: 'builder-org-member', isPrimary: true }],
    organizationId: 'org-001',
    organizationName: 'Horizon Builders',
    builderId: 'bld-001',
    builderName: 'Horizon Builders',
    mfaEnabled: false,
    emailVerified: false,
    sessionCount: 0,
    permissionCount: 5,
    invitationStatus: 'pending',
    createdAt: '2026-07-08T00:00:00Z',
    updatedAt: '2026-07-08T00:00:00Z',
  },
  {
    id: 'usr-007',
    email: 'support@mypropertyasset.com',
    displayName: 'Alex Morgan',
    firstName: 'Alex',
    lastName: 'Morgan',
    status: 'active',
    primaryRole: 'support-user',
    memberships: [{ organizationId: 'org-platform', organizationName: 'MyPropertyAsset Platform', organizationType: 'platform', role: 'support-user', isPrimary: true }],
    organizationId: 'org-platform',
    organizationName: 'MyPropertyAsset Platform',
    lastLoginAt: '2026-07-13T06:00:00Z',
    mfaEnabled: true,
    emailVerified: true,
    sessionCount: 1,
    permissionCount: 8,
    invitationStatus: 'accepted',
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2026-07-13T06:00:00Z',
  },
  {
    id: 'usr-008',
    email: 'former.user@example.com',
    displayName: 'Former User',
    status: 'archived',
    primaryRole: 'builder-org-member',
    memberships: [],
    mfaEnabled: false,
    emailVerified: true,
    sessionCount: 0,
    permissionCount: 0,
    invitationStatus: 'none',
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
  },
];

export const MOCK_USER_ACTIVITIES: readonly UserActivityRecord[] = [
  { id: 'ua-1', userId: 'usr-001', title: 'Signed in', description: 'Successful login from Chrome on Windows', timestamp: '2026-07-13T08:30:00Z', type: 'login' },
  { id: 'ua-2', userId: 'usr-001', title: 'Role reviewed', description: 'Super Admin permissions verified', timestamp: '2026-07-12T14:00:00Z', type: 'role' },
  { id: 'ua-3', userId: 'usr-002', title: 'Signed in', description: 'Successful login from Safari on macOS', timestamp: '2026-07-12T14:22:00Z', type: 'login' },
  { id: 'ua-4', userId: 'usr-006', title: 'Invitation sent', description: 'Pending activation invitation delivered', timestamp: '2026-07-08T00:00:00Z', type: 'invitation' },
];

export const MOCK_USER_STATUS_HISTORY: readonly UserStatusHistoryRecord[] = [
  { id: 'ush-1', userId: 'usr-006', status: 'pending', changedAt: '2026-07-08T00:00:00Z', changedBy: 'Sarah Chen', reason: 'User invited' },
  { id: 'ush-2', userId: 'usr-008', status: 'archived', changedAt: '2026-01-15T00:00:00Z', changedBy: 'Sarah Chen', reason: 'Account decommissioned' },
];

export const MOCK_USER_AUDITS: readonly UserAuditRecord[] = [
  { id: 'uau-1', userId: 'usr-001', action: 'Permission reviewed', actor: 'Sarah Chen', timestamp: '2026-07-12T14:00:00Z', detail: 'Full platform access confirmed' },
  { id: 'uau-2', userId: 'usr-006', action: 'Invitation created', actor: 'Marcus Rivera', timestamp: '2026-07-08T00:00:00Z', detail: 'Builder org member invitation' },
];

export const MOCK_INVITATIONS: readonly InvitationAdminRecord[] = [
  {
    id: 'inv-001',
    email: 'david.kim@horizonbuilders.com',
    name: 'David Kim',
    role: 'builder-org-member',
    organizationId: 'org-001',
    organizationName: 'Horizon Builders',
    builderId: 'bld-001',
    builderName: 'Horizon Builders',
    invitedBy: 'Marcus Rivera',
    invitedByEmail: 'marcus.rivera@horizonbuilders.com',
    status: 'pending',
    sentAt: '2026-07-08T00:00:00Z',
    expiresAt: '2026-07-22T00:00:00Z',
    resendCount: 1,
  },
  {
    id: 'inv-002',
    email: 'new.admin@skylinedevelopments.com',
    name: 'New Admin',
    role: 'builder-org-admin',
    organizationId: 'org-002',
    organizationName: 'Skyline Developments',
    builderId: 'bld-002',
    builderName: 'Skyline Developments',
    invitedBy: 'James Okonkwo',
    invitedByEmail: 'james.okonkwo@skylinedevelopments.com',
    status: 'pending',
    sentAt: '2026-07-10T00:00:00Z',
    expiresAt: '2026-07-24T00:00:00Z',
    resendCount: 0,
  },
  {
    id: 'inv-003',
    email: 'priya.sharma@horizonbuilders.com',
    name: 'Priya Sharma',
    role: 'builder-org-admin',
    organizationId: 'org-001',
    organizationName: 'Horizon Builders',
    invitedBy: 'Marcus Rivera',
    invitedByEmail: 'marcus.rivera@horizonbuilders.com',
    status: 'accepted',
    sentAt: '2024-06-08T00:00:00Z',
    expiresAt: '2024-06-22T00:00:00Z',
    acceptedAt: '2024-06-10T00:00:00Z',
    resendCount: 0,
  },
  {
    id: 'inv-004',
    email: 'expired@example.com',
    role: 'builder-org-member',
    organizationId: 'org-001',
    organizationName: 'Horizon Builders',
    invitedBy: 'Marcus Rivera',
    invitedByEmail: 'marcus.rivera@horizonbuilders.com',
    status: 'expired',
    sentAt: '2026-05-01T00:00:00Z',
    expiresAt: '2026-05-15T00:00:00Z',
    resendCount: 2,
  },
  {
    id: 'inv-005',
    email: 'cancelled@example.com',
    role: 'owner-web-user',
    organizationId: 'org-003',
    organizationName: 'Capital Owners Group',
    invitedBy: 'Elena Vasquez',
    invitedByEmail: 'elena.vasquez@capitalowners.com',
    status: 'cancelled',
    sentAt: '2026-06-01T00:00:00Z',
    expiresAt: '2026-06-15T00:00:00Z',
    cancelledAt: '2026-06-05T00:00:00Z',
    resendCount: 0,
  },
];

export const MOCK_INVITATION_TIMELINE: readonly InvitationTimelineEvent[] = [
  { id: 'it-1', invitationId: 'inv-001', title: 'Invitation sent', description: 'Email delivered to david.kim@horizonbuilders.com', timestamp: '2026-07-08T00:00:00Z', type: 'sent' },
  { id: 'it-2', invitationId: 'inv-001', title: 'Invitation resent', description: 'Reminder email sent', timestamp: '2026-07-12T00:00:00Z', type: 'resent' },
  { id: 'it-3', invitationId: 'inv-003', title: 'Invitation accepted', description: 'User completed onboarding', timestamp: '2024-06-10T00:00:00Z', type: 'accepted' },
];

export const ROLE_USER_COUNTS: Partial<Record<PlatformRole, number>> = {
  'super-admin': 1,
  'builder-org-owner': 2,
  'builder-org-admin': 1,
  'builder-org-member': 2,
  'owner-org-owner': 1,
  'support-user': 1,
};
