import {
  BillingSectionId,
  CommercialAlert,
  InvoiceRecord,
  LicensePool,
  PaymentProviderPlaceholder,
  SubscriptionPlan,
  SubscriptionRecord,
  SubscriptionTimelineEvent,
  UsageMetric,
} from '../models/billing-admin.model';

export const BILLING_SECTIONS: readonly {
  id: BillingSectionId;
  label: string;
  icon: string;
  route: string;
}[] = [
  { id: 'dashboard', label: 'Overview', icon: 'pi pi-th-large', route: '/super-admin/billing' },
  { id: 'plans', label: 'Plans', icon: 'pi pi-box', route: '/super-admin/billing/plans' },
  { id: 'billing', label: 'Invoices', icon: 'pi pi-file', route: '/super-admin/billing/invoices' },
  { id: 'licenses', label: 'Licenses', icon: 'pi pi-key', route: '/super-admin/billing/licenses' },
  { id: 'usage', label: 'Usage', icon: 'pi pi-chart-bar', route: '/super-admin/billing/usage' },
  {
    id: 'notifications',
    label: 'Alerts',
    icon: 'pi pi-bell',
    route: '/super-admin/billing/notifications',
  },
];

const feature = (id: string, label: string, included: boolean, highlight = false) => ({
  id,
  label,
  included,
  highlight,
});

export const MOCK_PLANS: readonly SubscriptionPlan[] = [
  {
    id: 'plan-starter',
    tier: 'starter',
    name: 'Starter',
    description: 'For emerging builder organizations getting started on the platform.',
    monthlyPrice: 14900,
    annualPrice: 149000,
    currency: 'INR',
    features: [
      feature('f1', '1 organization', true),
      feature('f2', '10 user seats', true),
      feature('f3', '50 GB storage', true),
      feature('f4', 'White-label branding', false),
      feature('f5', 'Priority support', false),
      feature('f6', 'SSO / SAML', false),
    ],
    limits: { organizations: 1, users: 10, storageGb: 50, projects: 5, units: 100, apiCalls: 10000 },
  },
  {
    id: 'plan-growth',
    tier: 'growth',
    name: 'Growth',
    description: 'Scale operations across projects with advanced branding and support.',
    monthlyPrice: 39900,
    annualPrice: 399000,
    currency: 'INR',
    popular: true,
    features: [
      feature('f1', '5 organizations', true, true),
      feature('f2', '50 user seats', true),
      feature('f3', '250 GB storage', true),
      feature('f4', 'White-label branding', true, true),
      feature('f5', 'Priority support', true),
      feature('f6', 'SSO / SAML', false),
    ],
    limits: {
      organizations: 5,
      users: 50,
      storageGb: 250,
      projects: 25,
      units: 1000,
      apiCalls: 100000,
    },
  },
  {
    id: 'plan-business',
    tier: 'business',
    name: 'Business',
    description: 'Multi-tenant builders with governance, SSO, and higher limits.',
    monthlyPrice: 79900,
    annualPrice: 799000,
    currency: 'INR',
    features: [
      feature('f1', '20 organizations', true),
      feature('f2', '200 user seats', true),
      feature('f3', '1 TB storage', true),
      feature('f4', 'White-label branding', true),
      feature('f5', 'Priority support', true),
      feature('f6', 'SSO / SAML', true, true),
    ],
    limits: {
      organizations: 20,
      users: 200,
      storageGb: 1024,
      projects: 100,
      units: 5000,
      apiCalls: 500000,
    },
  },
  {
    id: 'plan-enterprise',
    tier: 'enterprise',
    name: 'Enterprise',
    description: 'Custom licensing, dedicated success, and enterprise billing agreements.',
    monthlyPrice: 0,
    annualPrice: 0,
    currency: 'INR',
    enterprise: true,
    features: [
      feature('f1', 'Unlimited organizations', true),
      feature('f2', 'Custom seat packs', true),
      feature('f3', 'Unlimited storage', true),
      feature('f4', 'White-label branding', true),
      feature('f5', 'Dedicated success manager', true, true),
      feature('f6', 'SSO / SAML + SCIM', true),
    ],
    limits: {
      organizations: 9999,
      users: 9999,
      storageGb: 9999,
      projects: 9999,
      units: 9999,
      apiCalls: 9999999,
    },
  },
];

export const MOCK_SUBSCRIPTIONS: readonly SubscriptionRecord[] = [
  {
    id: 'sub-horizon',
    organizationId: 'org-horizon',
    organizationName: 'Horizon Builders',
    builderId: 'builder-horizon',
    builderName: 'Horizon Builders Pvt Ltd',
    planId: 'plan-growth',
    planName: 'Growth',
    tier: 'growth',
    status: 'active',
    interval: 'annual',
    amount: 399000,
    currency: 'INR',
    startDate: '2025-08-01T00:00:00Z',
    renewsAt: '2026-08-01T00:00:00Z',
    seats: 50,
    seatsUsed: 38,
  },
  {
    id: 'sub-skyline',
    organizationId: 'org-skyline',
    organizationName: 'Skyline Residences',
    planId: 'plan-starter',
    planName: 'Starter',
    tier: 'starter',
    status: 'trial',
    interval: 'monthly',
    amount: 14900,
    currency: 'INR',
    startDate: '2026-06-20T00:00:00Z',
    renewsAt: '2026-07-20T00:00:00Z',
    trialEndsAt: '2026-07-20T00:00:00Z',
    seats: 10,
    seatsUsed: 7,
  },
  {
    id: 'sub-apex',
    organizationId: 'org-apex',
    organizationName: 'Apex Developments',
    builderId: 'builder-apex',
    builderName: 'Apex Developments Ltd',
    planId: 'plan-business',
    planName: 'Business',
    tier: 'business',
    status: 'past_due',
    interval: 'annual',
    amount: 799000,
    currency: 'INR',
    startDate: '2025-04-15T00:00:00Z',
    renewsAt: '2026-04-15T00:00:00Z',
    seats: 200,
    seatsUsed: 165,
  },
];

export const MOCK_INVOICES: readonly InvoiceRecord[] = [
  {
    id: 'inv-1001',
    number: 'INV-2026-1001',
    subscriptionId: 'sub-horizon',
    organizationName: 'Horizon Builders',
    status: 'paid',
    paymentStatus: 'succeeded',
    currency: 'INR',
    subtotal: 399000,
    tax: 71820,
    total: 470820,
    issuedAt: '2025-08-01T10:00:00Z',
    dueAt: '2025-08-15T00:00:00Z',
    paidAt: '2025-08-03T14:22:00Z',
    billingAddress: {
      line1: '12 Brigade Road',
      city: 'Bengaluru',
      region: 'KA',
      postalCode: '560001',
      country: 'IN',
    },
    taxId: '29AABCH1234A1Z5',
    lines: [
      {
        id: 'l1',
        description: 'Growth plan — annual',
        quantity: 1,
        unitAmount: 399000,
        amount: 399000,
      },
    ],
  },
  {
    id: 'inv-1002',
    number: 'INV-2026-1002',
    subscriptionId: 'sub-apex',
    organizationName: 'Apex Developments',
    status: 'past_due',
    paymentStatus: 'failed',
    currency: 'INR',
    subtotal: 799000,
    tax: 143820,
    total: 942820,
    issuedAt: '2026-04-01T10:00:00Z',
    dueAt: '2026-04-15T00:00:00Z',
    billingAddress: {
      line1: '88 Marine Drive',
      city: 'Mumbai',
      region: 'MH',
      postalCode: '400020',
      country: 'IN',
    },
    taxId: '27AABCA9999B1Z0',
    lines: [
      {
        id: 'l1',
        description: 'Business plan — annual',
        quantity: 1,
        unitAmount: 799000,
        amount: 799000,
      },
    ],
  },
  {
    id: 'inv-1003',
    number: 'INV-2026-1003',
    subscriptionId: 'sub-skyline',
    organizationName: 'Skyline Residences',
    status: 'open',
    paymentStatus: 'pending',
    currency: 'INR',
    subtotal: 14900,
    tax: 2682,
    total: 17582,
    issuedAt: '2026-07-01T09:00:00Z',
    dueAt: '2026-07-15T00:00:00Z',
    billingAddress: {
      line1: '45 Jubilee Hills',
      city: 'Hyderabad',
      region: 'TG',
      postalCode: '500033',
      country: 'IN',
    },
    lines: [
      {
        id: 'l1',
        description: 'Starter plan — monthly (post-trial)',
        quantity: 1,
        unitAmount: 14900,
        amount: 14900,
      },
    ],
  },
];

export const MOCK_LICENSES: readonly LicensePool[] = [
  {
    id: 'lic-horizon',
    organizationId: 'org-horizon',
    organizationName: 'Horizon Builders',
    product: 'Platform seats',
    status: 'active',
    allocated: 50,
    used: 38,
    available: 12,
    expiresAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'lic-skyline',
    organizationId: 'org-skyline',
    organizationName: 'Skyline Residences',
    product: 'Platform seats',
    status: 'expiring',
    allocated: 10,
    used: 7,
    available: 3,
    expiresAt: '2026-07-20T00:00:00Z',
  },
  {
    id: 'lic-apex',
    organizationId: 'org-apex',
    organizationName: 'Apex Developments',
    product: 'Platform seats',
    status: 'exhausted',
    allocated: 200,
    used: 198,
    available: 2,
    expiresAt: '2026-04-15T00:00:00Z',
  },
];

export const MOCK_USAGE: readonly UsageMetric[] = [
  { key: 'organizations', label: 'Organizations', used: 3, limit: 5, unit: 'orgs' },
  { key: 'users', label: 'Users', used: 210, limit: 260, unit: 'seats' },
  { key: 'storage', label: 'Storage', used: 186, limit: 250, unit: 'GB' },
  { key: 'projects', label: 'Projects', used: 18, limit: 25, unit: 'projects', placeholder: true },
  { key: 'units', label: 'Units', used: 420, limit: 1000, unit: 'units', placeholder: true },
  { key: 'api', label: 'API calls', used: 42000, limit: 100000, unit: 'calls / mo', placeholder: true },
];

export const MOCK_TIMELINE: readonly SubscriptionTimelineEvent[] = [
  {
    id: 't1',
    title: 'Growth plan renewed',
    description: 'Horizon Builders annual renewal processed successfully.',
    timestamp: '2025-08-01T10:00:00Z',
    kind: 'renewal',
  },
  {
    id: 't2',
    title: 'Trial started',
    description: 'Skyline Residences began a 30-day Starter trial.',
    timestamp: '2026-06-20T08:00:00Z',
    kind: 'trial',
  },
  {
    id: 't3',
    title: 'Invoice past due',
    description: 'Apex Developments Business plan invoice INV-2026-1002 is past due.',
    timestamp: '2026-04-16T00:00:00Z',
    kind: 'invoice',
  },
  {
    id: 't4',
    title: 'License nearly exhausted',
    description: 'Apex Developments has 2 seats remaining.',
    timestamp: '2026-07-10T12:00:00Z',
    kind: 'license',
  },
];

export const MOCK_ALERTS: readonly CommercialAlert[] = [
  {
    id: 'a1',
    type: 'trial_expiry',
    title: 'Trial ending soon',
    message: 'Skyline Residences trial ends on 20 Jul 2026.',
    severity: 'warning',
    organizationName: 'Skyline Residences',
    createdAt: '2026-07-12T09:00:00Z',
    acknowledged: false,
    actionLabel: 'View plan',
    actionRoute: '/super-admin/billing/plans',
  },
  {
    id: 'a2',
    type: 'payment_due',
    title: 'Payment failed',
    message: 'Apex Developments invoice INV-2026-1002 requires attention.',
    severity: 'critical',
    organizationName: 'Apex Developments',
    createdAt: '2026-04-16T08:00:00Z',
    acknowledged: false,
    actionLabel: 'Open invoice',
    actionRoute: '/super-admin/billing/invoices/inv-1002',
  },
  {
    id: 'a3',
    type: 'license_exhaustion',
    title: 'Seats nearly exhausted',
    message: 'Apex Developments has only 2 licenses available.',
    severity: 'warning',
    organizationName: 'Apex Developments',
    createdAt: '2026-07-10T12:00:00Z',
    acknowledged: false,
    actionLabel: 'Manage licenses',
    actionRoute: '/super-admin/billing/licenses',
  },
  {
    id: 'a4',
    type: 'upgrade_recommendation',
    title: 'Upgrade recommended',
    message: 'Horizon Builders is nearing Growth org limits. Consider Business.',
    severity: 'info',
    organizationName: 'Horizon Builders',
    createdAt: '2026-07-08T11:00:00Z',
    acknowledged: true,
    actionLabel: 'Compare plans',
    actionRoute: '/super-admin/billing/plans',
  },
  {
    id: 'a5',
    type: 'renewal_reminder',
    title: 'Renewal in 18 days',
    message: 'Horizon Builders Growth annual plan renews on 1 Aug 2026.',
    severity: 'info',
    organizationName: 'Horizon Builders',
    createdAt: '2026-07-13T07:00:00Z',
    acknowledged: false,
  },
];

export const PAYMENT_PROVIDERS: readonly PaymentProviderPlaceholder[] = [
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Global card and subscription billing.',
    status: 'planned',
    icon: 'pi pi-credit-card',
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    description: 'India-first UPI, cards, and subscriptions.',
    status: 'planned',
    icon: 'pi pi-wallet',
  },
  {
    id: 'paddle',
    name: 'Paddle',
    description: 'Merchant of record for SaaS checkout.',
    status: 'coming_soon',
    icon: 'pi pi-shopping-bag',
  },
  {
    id: 'cashfree',
    name: 'Cashfree',
    description: 'Indian payments and payouts.',
    status: 'coming_soon',
    icon: 'pi pi-money-bill',
  },
  {
    id: 'phonepe',
    name: 'PhonePe',
    description: 'UPI and consumer payment rails.',
    status: 'coming_soon',
    icon: 'pi pi-mobile',
  },
  {
    id: 'enterprise',
    name: 'Enterprise Billing',
    description: 'PO-based and custom contract invoicing.',
    status: 'enterprise_only',
    icon: 'pi pi-briefcase',
  },
];

export const formatMoney = (amount: number, currency = 'INR'): string => {
  try {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency,
      maximumFractionDigits: 0,
    }).format(amount / (currency === 'INR' ? 1 : 1));
  } catch {
    return `${currency} ${amount}`;
  }
};

/** Amounts stored in minor units for INR paise would be /100; mock uses whole rupees. */
export const formatRupees = (amount: number): string =>
  new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
