import {
  Project,
  emptyProjectSummary,
} from '../models/project.model';

const ORG = {
  organizationId: 'org-builder-demo',
  organizationName: 'Horizon Builders',
};

export const SEED_BUILDER_PROJECTS: readonly Project[] = [
  {
    id: 'proj-001',
    name: 'Horizon Towers',
    code: 'HZT-01',
    description: 'Twin residential towers with integrated retail podium.',
    ...ORG,
    projectType: 'apartment',
    hierarchy: 'building-based',
    status: 'construction',
    location: {
      addressLine: 'Plot 14, Sector 12',
      city: 'Gurugram',
      state: 'Haryana',
      postalCode: '122001',
      latitude: 28.4595,
      longitude: 77.0266,
    },
    launchDate: '2025-02-10',
    expectedCompletionDate: '2027-03-31',
    summary: {
      ...emptyProjectSummary(),
      unitsTotal: 240,
      unitsSold: 168,
      ownersCount: 168,
      documentsCount: 512,
      openSnags: 14,
      upcomingAppointments: 3,
    },
    archived: false,
    createdAt: '2025-02-01T09:00:00Z',
    updatedAt: '2026-07-12T10:00:00Z',
  },
  {
    id: 'proj-002',
    name: 'Skyline Residences',
    code: 'SKR-02',
    description: 'Premium mid-rise apartments nearing completion.',
    ...ORG,
    projectType: 'apartment',
    hierarchy: 'building-based',
    status: 'construction',
    location: {
      addressLine: '22 Baner Road',
      city: 'Pune',
      state: 'Maharashtra',
      postalCode: '411045',
      latitude: 18.559,
      longitude: 73.7868,
    },
    launchDate: '2023-11-01',
    expectedCompletionDate: '2026-08-31',
    summary: {
      ...emptyProjectSummary(),
      unitsTotal: 160,
      unitsSold: 160,
      ownersCount: 160,
      documentsCount: 640,
      pendingHandovers: 12,
      openSnags: 6,
      upcomingAppointments: 5,
    },
    archived: false,
    createdAt: '2023-10-20T09:00:00Z',
    updatedAt: '2026-07-11T08:00:00Z',
  },
  {
    id: 'proj-003',
    name: 'Meadow Heights',
    code: 'MDH-03',
    description: 'Large-scale mixed township with phased delivery.',
    ...ORG,
    projectType: 'mixed-development',
    hierarchy: 'building-based',
    status: 'construction',
    location: {
      addressLine: '5 Whitefield Main Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560066',
      latitude: 12.9698,
      longitude: 77.75,
    },
    launchDate: '2024-06-01',
    expectedCompletionDate: '2027-12-31',
    summary: {
      ...emptyProjectSummary(),
      unitsTotal: 320,
      unitsSold: 210,
      ownersCount: 210,
      documentsCount: 448,
      openSnags: 31,
      upcomingAppointments: 2,
    },
    archived: false,
    createdAt: '2024-05-20T09:00:00Z',
    updatedAt: '2026-07-10T14:00:00Z',
  },
  {
    id: 'proj-004',
    name: 'Emerald Court',
    code: 'EMC-04',
    description: 'Boutique residential development in early planning.',
    ...ORG,
    projectType: 'apartment',
    hierarchy: 'building-based',
    status: 'planning',
    location: {
      addressLine: '9 Kandivali West',
      city: 'Mumbai',
      state: 'Maharashtra',
      postalCode: '400067',
      latitude: 19.2094,
      longitude: 72.8526,
    },
    launchDate: '2026-05-01',
    expectedCompletionDate: '2029-05-01',
    summary: {
      ...emptyProjectSummary(),
      unitsTotal: 96,
      unitsSold: 12,
      ownersCount: 12,
      documentsCount: 40,
      upcomingAppointments: 1,
    },
    archived: false,
    createdAt: '2026-04-15T09:00:00Z',
    updatedAt: '2026-07-09T11:00:00Z',
  },
  {
    id: 'proj-005',
    name: 'Riverside Grove',
    code: 'RVG-05',
    description: 'Waterfront villas with private gardens.',
    ...ORG,
    projectType: 'villa',
    hierarchy: 'direct-units',
    status: 'upcoming',
    location: {
      addressLine: '3 Riverside Drive',
      city: 'Ahmedabad',
      state: 'Gujarat',
      postalCode: '380015',
      latitude: 23.0225,
      longitude: 72.5714,
    },
    launchDate: '2025-09-01',
    expectedCompletionDate: '2028-03-01',
    summary: {
      ...emptyProjectSummary(),
      unitsTotal: 64,
      unitsSold: 22,
      ownersCount: 22,
      documentsCount: 88,
      openSnags: 9,
    },
    archived: false,
    createdAt: '2025-08-20T09:00:00Z',
    updatedAt: '2026-07-08T09:30:00Z',
  },
  {
    id: 'proj-006',
    name: 'Pinehill Estates',
    code: 'PHE-06',
    description: 'Completed hillside community.',
    ...ORG,
    projectType: 'villa',
    hierarchy: 'direct-units',
    status: 'completed',
    location: {
      addressLine: '1 Pinehill Road',
      city: 'Shimla',
      state: 'Himachal Pradesh',
      postalCode: '171001',
      latitude: 31.1048,
      longitude: 77.1734,
    },
    launchDate: '2022-01-01',
    expectedCompletionDate: '2025-12-31',
    summary: {
      ...emptyProjectSummary(),
      unitsTotal: 48,
      unitsSold: 48,
      ownersCount: 48,
      documentsCount: 210,
    },
    archived: false,
    createdAt: '2021-12-01T09:00:00Z',
    updatedAt: '2025-11-30T09:00:00Z',
  },
  {
    id: 'proj-007',
    name: 'Cedar Business Park',
    code: 'CBP-07',
    description: 'Commercial campus with retail podium.',
    ...ORG,
    projectType: 'commercial',
    hierarchy: 'building-based',
    status: 'construction',
    location: {
      addressLine: '77 Cedar Avenue',
      city: 'Noida',
      state: 'Uttar Pradesh',
      postalCode: '201301',
      latitude: 28.5355,
      longitude: 77.391,
    },
    launchDate: '2024-11-01',
    expectedCompletionDate: '2027-06-30',
    summary: {
      ...emptyProjectSummary(),
      unitsTotal: 180,
      unitsSold: 96,
      ownersCount: 96,
      documentsCount: 302,
      openSnags: 18,
      upcomingAppointments: 4,
    },
    archived: false,
    createdAt: '2024-10-15T09:00:00Z',
    updatedAt: '2026-07-06T15:00:00Z',
  },
  {
    id: 'proj-008',
    name: 'Willow Creek Plots',
    code: 'WCV-08',
    description: 'Archived residential plot scheme.',
    ...ORG,
    projectType: 'residential-plot',
    hierarchy: 'direct-units',
    status: 'archived',
    location: {
      addressLine: '2 Willow Creek Lane',
      city: 'Chandigarh',
      state: 'Punjab',
      postalCode: '160002',
      latitude: 30.7333,
      longitude: 76.7794,
    },
    launchDate: '2024-01-01',
    expectedCompletionDate: '2026-12-31',
    summary: emptyProjectSummary(),
    archived: true,
    createdAt: '2023-12-01T09:00:00Z',
    updatedAt: '2025-03-01T09:00:00Z',
  },
];
