import { DashboardActivityItem, DashboardKpiItem, DashboardQuickActionItem } from '../../models/dashboard.model';
import { Project, ProjectSavedView, ProjectTableColumn } from '../models/project.model';

export const PROJECT_WORKSPACE_HEADER = {
  eyebrow: 'Builder Portal',
  title: 'Project workspace',
  description: 'A portfolio-wide view of construction progress, health, and delivery milestones.',
};

export const PROJECT_TABLE_COLUMNS: readonly ProjectTableColumn[] = [
  { id: 'name', label: 'Project', sortable: true, defaultVisible: true },
  { id: 'status', label: 'Status', sortable: true, defaultVisible: true },
  { id: 'constructionStage', label: 'Construction stage', sortable: true, defaultVisible: true },
  { id: 'health', label: 'Health', sortable: true, defaultVisible: true },
  { id: 'progress', label: 'Progress', sortable: true, defaultVisible: true },
  { id: 'units', label: 'Units', sortable: false, defaultVisible: true },
  { id: 'city', label: 'Location', sortable: true, defaultVisible: false },
  { id: 'targetCompletionDate', label: 'Target completion', sortable: true, defaultVisible: false },
];

export const PROJECT_SAVED_VIEWS: readonly ProjectSavedView[] = [
  { id: 'all', name: 'All projects', statusFilter: 'all', healthFilter: 'all', isDefault: true },
  { id: 'in-progress', name: 'In progress', statusFilter: 'in-progress', healthFilter: 'all' },
  { id: 'at-risk', name: 'At risk', statusFilter: 'all', healthFilter: 'at-risk' },
  { id: 'nearing-handover', name: 'Nearing handover', statusFilter: 'handover', healthFilter: 'all' },
];

export const PROJECT_STATUS_OPTIONS = [
  { label: 'All statuses', value: 'all' },
  { label: 'Planning', value: 'planning' },
  { label: 'In progress', value: 'in-progress' },
  { label: 'Handover', value: 'handover' },
  { label: 'Completed', value: 'completed' },
] as const;

export const PROJECT_STAGE_OPTIONS = [
  { label: 'All stages', value: 'all' },
  { label: 'Land acquisition', value: 'land-acquisition' },
  { label: 'Foundation', value: 'foundation' },
  { label: 'Structure', value: 'structure' },
  { label: 'Finishing', value: 'finishing' },
  { label: 'Handover', value: 'handover' },
  { label: 'Completed', value: 'completed' },
] as const;

export const PROJECT_HEALTH_OPTIONS = [
  { label: 'All health', value: 'all' },
  { label: 'On track', value: 'on-track' },
  { label: 'At risk', value: 'at-risk' },
  { label: 'Delayed', value: 'delayed' },
] as const;

export const PROJECT_SORT_OPTIONS = [
  { label: 'Name A–Z', value: 'name:asc' },
  { label: 'Name Z–A', value: 'name:desc' },
  { label: 'Newest', value: 'createdAt:desc' },
  { label: 'Target completion', value: 'targetCompletionDate:asc' },
  { label: 'Progress', value: 'progress:desc' },
] as const;

export const PROJECT_WORKSPACE_KPIS: readonly DashboardKpiItem[] = [
  {
    id: 'active-projects',
    label: 'Active projects',
    value: '9',
    hint: 'Currently under construction',
    icon: 'pi pi-briefcase',
    tone: 'primary',
    trend: 'up',
    trendLabel: '+2 this quarter',
  },
  {
    id: 'avg-progress',
    label: 'Avg. progress',
    value: '58%',
    hint: 'Across active projects',
    icon: 'pi pi-gauge',
    tone: 'info',
    trend: 'up',
    trendLabel: '+4% this month',
  },
  {
    id: 'at-risk',
    label: 'At risk',
    value: '2',
    hint: 'Needs attention',
    icon: 'pi pi-exclamation-triangle',
    tone: 'warning',
    trend: 'neutral',
    trendLabel: 'Unchanged',
  },
  {
    id: 'nearing-handover',
    label: 'Nearing handover',
    value: '3',
    hint: 'Target completion within 60 days',
    icon: 'pi pi-key',
    tone: 'success',
    trend: 'up',
    trendLabel: '+1 vs last month',
  },
];

export const PROJECT_WORKSPACE_QUICK_ACTIONS: readonly DashboardQuickActionItem[] = [
  {
    id: 'pqa1',
    label: 'Create project',
    description: 'Start a new development',
    icon: 'pi pi-plus-circle',
    route: '/builder-portal/projects/create',
    permission: 'id-07-project-unit:full',
    pinned: true,
    favorite: true,
  },
  {
    id: 'pqa2',
    label: 'Browse all projects',
    description: 'Enterprise grid with filters',
    icon: 'pi pi-th-large',
    route: '/builder-portal/projects/list',
    permission: 'id-07-project-unit:read',
    pinned: true,
  },
  {
    id: 'pqa3',
    label: 'Nearing handover',
    description: 'Projects due within 60 days',
    icon: 'pi pi-key',
    route: '/builder-portal/projects/list',
    permission: 'id-07-project-unit:read',
    favorite: true,
  },
];

export const PROJECT_WORKSPACE_ACTIVITIES: readonly DashboardActivityItem[] = [
  {
    id: 'pa1',
    title: 'Milestone completed',
    description: 'Structure stage completed at Horizon Towers.',
    timestamp: '2 hours ago',
    icon: 'pi pi-flag',
    tone: 'success',
  },
  {
    id: 'pa2',
    title: 'Health flagged at risk',
    description: 'Meadow Heights slipped behind schedule.',
    timestamp: '5 hours ago',
    icon: 'pi pi-exclamation-triangle',
    tone: 'warning',
  },
  {
    id: 'pa3',
    title: 'New project created',
    description: 'Emerald Court entered planning.',
    timestamp: '1 day ago',
    icon: 'pi pi-plus-circle',
    tone: 'primary',
  },
];

export const MOCK_PROJECTS: readonly Project[] = [
  {
    id: 'proj-001',
    name: 'Horizon Towers',
    code: 'HZT-01',
    description: 'Twin residential towers with integrated retail podium.',
    organizationId: 'org-current',
    organizationName: 'Apex Developments',
    status: 'in-progress',
    constructionStage: 'structure',
    health: 'on-track',
    progress: 62,
    location: { addressLine: 'Plot 14, Sector 12', city: 'Gurugram', state: 'Haryana', postalCode: '122001', country: 'India' },
    startDate: '2025-02-10',
    targetCompletionDate: '2027-03-31',
    milestones: [
      { id: 'm1', label: 'Land acquisition', date: '2025-02-10', status: 'completed' },
      { id: 'm2', label: 'Foundation complete', date: '2025-08-15', status: 'completed' },
      { id: 'm3', label: 'Structure complete', date: '2026-09-30', status: 'in-progress' },
      { id: 'm4', label: 'Finishing', date: '2027-01-15', status: 'upcoming' },
      { id: 'm5', label: 'Handover', date: '2027-03-31', status: 'upcoming' },
    ],
    summary: { unitsTotal: 240, unitsSold: 168, ownersCount: 168, documentsCount: 512, pendingHandovers: 0, openSnags: 14, upcomingAppointments: 3 },
    archived: false,
    createdAt: '2025-02-01T09:00:00Z',
    updatedAt: '2026-07-12T10:00:00Z',
  },
  {
    id: 'proj-002',
    name: 'Skyline Residences',
    code: 'SKR-02',
    description: 'Premium mid-rise apartments nearing handover.',
    organizationId: 'org-current',
    organizationName: 'Apex Developments',
    status: 'handover',
    constructionStage: 'handover',
    health: 'on-track',
    progress: 88,
    location: { addressLine: '22 Baner Road', city: 'Pune', state: 'Maharashtra', postalCode: '411045', country: 'India' },
    startDate: '2023-11-01',
    targetCompletionDate: '2026-08-31',
    milestones: [
      { id: 'm1', label: 'Land acquisition', date: '2023-11-01', status: 'completed' },
      { id: 'm2', label: 'Foundation complete', date: '2024-04-01', status: 'completed' },
      { id: 'm3', label: 'Structure complete', date: '2025-06-01', status: 'completed' },
      { id: 'm4', label: 'Finishing complete', date: '2026-05-01', status: 'completed' },
      { id: 'm5', label: 'Handover', date: '2026-08-31', status: 'in-progress' },
    ],
    summary: { unitsTotal: 160, unitsSold: 160, ownersCount: 160, documentsCount: 640, pendingHandovers: 12, openSnags: 6, upcomingAppointments: 5 },
    archived: false,
    createdAt: '2023-10-20T09:00:00Z',
    updatedAt: '2026-07-11T08:00:00Z',
  },
  {
    id: 'proj-003',
    name: 'Meadow Heights',
    code: 'MDH-03',
    description: 'Large-scale township with phased delivery.',
    organizationId: 'org-current',
    organizationName: 'Apex Developments',
    status: 'in-progress',
    constructionStage: 'finishing',
    health: 'at-risk',
    progress: 41,
    location: { addressLine: '5 Whitefield Main Road', city: 'Bengaluru', state: 'Karnataka', postalCode: '560066', country: 'India' },
    startDate: '2024-06-01',
    targetCompletionDate: '2027-12-31',
    milestones: [
      { id: 'm1', label: 'Land acquisition', date: '2024-06-01', status: 'completed' },
      { id: 'm2', label: 'Foundation complete', date: '2025-01-15', status: 'completed' },
      { id: 'm3', label: 'Structure complete', date: '2026-03-01', status: 'completed' },
      { id: 'm4', label: 'Finishing', date: '2027-06-01', status: 'in-progress' },
      { id: 'm5', label: 'Handover', date: '2027-12-31', status: 'upcoming' },
    ],
    summary: { unitsTotal: 320, unitsSold: 210, ownersCount: 210, documentsCount: 448, pendingHandovers: 0, openSnags: 31, upcomingAppointments: 2 },
    archived: false,
    createdAt: '2024-05-20T09:00:00Z',
    updatedAt: '2026-07-10T14:00:00Z',
  },
  {
    id: 'proj-004',
    name: 'Emerald Court',
    code: 'EMC-04',
    description: 'Boutique residential development in early planning.',
    organizationId: 'org-current',
    organizationName: 'Apex Developments',
    status: 'planning',
    constructionStage: 'land-acquisition',
    health: 'on-track',
    progress: 8,
    location: { addressLine: '9 Kandivali West', city: 'Mumbai', state: 'Maharashtra', postalCode: '400067', country: 'India' },
    startDate: '2026-05-01',
    targetCompletionDate: '2029-05-01',
    milestones: [
      { id: 'm1', label: 'Land acquisition', date: '2026-05-01', status: 'in-progress' },
      { id: 'm2', label: 'Foundation', date: '2027-01-01', status: 'upcoming' },
      { id: 'm3', label: 'Structure', date: '2028-01-01', status: 'upcoming' },
      { id: 'm4', label: 'Finishing', date: '2028-10-01', status: 'upcoming' },
      { id: 'm5', label: 'Handover', date: '2029-05-01', status: 'upcoming' },
    ],
    summary: { unitsTotal: 96, unitsSold: 12, ownersCount: 12, documentsCount: 40, pendingHandovers: 0, openSnags: 0, upcomingAppointments: 1 },
    archived: false,
    createdAt: '2026-04-15T09:00:00Z',
    updatedAt: '2026-07-09T11:00:00Z',
  },
  {
    id: 'proj-005',
    name: 'Riverside Grove',
    code: 'RVG-05',
    description: 'Waterfront villas with private gardens.',
    organizationId: 'org-current',
    organizationName: 'Apex Developments',
    status: 'in-progress',
    constructionStage: 'foundation',
    health: 'delayed',
    progress: 22,
    location: { addressLine: '3 Riverside Drive', city: 'Ahmedabad', state: 'Gujarat', postalCode: '380015', country: 'India' },
    startDate: '2025-09-01',
    targetCompletionDate: '2028-03-01',
    milestones: [
      { id: 'm1', label: 'Land acquisition', date: '2025-09-01', status: 'completed' },
      { id: 'm2', label: 'Foundation', date: '2026-09-01', status: 'in-progress' },
      { id: 'm3', label: 'Structure', date: '2027-06-01', status: 'upcoming' },
      { id: 'm4', label: 'Finishing', date: '2027-12-01', status: 'upcoming' },
      { id: 'm5', label: 'Handover', date: '2028-03-01', status: 'upcoming' },
    ],
    summary: { unitsTotal: 64, unitsSold: 22, ownersCount: 22, documentsCount: 88, pendingHandovers: 0, openSnags: 9, upcomingAppointments: 0 },
    archived: false,
    createdAt: '2025-08-20T09:00:00Z',
    updatedAt: '2026-07-08T09:30:00Z',
  },
  {
    id: 'proj-006',
    name: 'Pinehill Estates',
    code: 'PHE-06',
    description: 'Completed hillside community, fully handed over.',
    organizationId: 'org-current',
    organizationName: 'Apex Developments',
    status: 'completed',
    constructionStage: 'completed',
    health: 'on-track',
    progress: 100,
    location: { addressLine: '1 Pinehill Road', city: 'Shimla', state: 'Himachal Pradesh', postalCode: '171001', country: 'India' },
    startDate: '2022-01-01',
    targetCompletionDate: '2025-12-31',
    actualCompletionDate: '2025-11-30',
    milestones: [
      { id: 'm1', label: 'Land acquisition', date: '2022-01-01', status: 'completed' },
      { id: 'm2', label: 'Foundation complete', date: '2022-08-01', status: 'completed' },
      { id: 'm3', label: 'Structure complete', date: '2023-10-01', status: 'completed' },
      { id: 'm4', label: 'Finishing complete', date: '2025-06-01', status: 'completed' },
      { id: 'm5', label: 'Handover complete', date: '2025-11-30', status: 'completed' },
    ],
    summary: { unitsTotal: 48, unitsSold: 48, ownersCount: 48, documentsCount: 210, pendingHandovers: 0, openSnags: 0, upcomingAppointments: 0 },
    archived: false,
    createdAt: '2021-12-01T09:00:00Z',
    updatedAt: '2025-11-30T09:00:00Z',
  },
  {
    id: 'proj-007',
    name: 'Cedar Business Park',
    code: 'CBP-07',
    description: 'Mixed-use commercial and residential complex.',
    organizationId: 'org-current',
    organizationName: 'Apex Developments',
    status: 'in-progress',
    constructionStage: 'structure',
    health: 'on-track',
    progress: 55,
    location: { addressLine: '77 Cedar Avenue', city: 'Noida', state: 'Uttar Pradesh', postalCode: '201301', country: 'India' },
    startDate: '2024-11-01',
    targetCompletionDate: '2027-06-30',
    milestones: [
      { id: 'm1', label: 'Land acquisition', date: '2024-11-01', status: 'completed' },
      { id: 'm2', label: 'Foundation complete', date: '2025-05-01', status: 'completed' },
      { id: 'm3', label: 'Structure', date: '2026-10-01', status: 'in-progress' },
      { id: 'm4', label: 'Finishing', date: '2027-03-01', status: 'upcoming' },
      { id: 'm5', label: 'Handover', date: '2027-06-30', status: 'upcoming' },
    ],
    summary: { unitsTotal: 180, unitsSold: 96, ownersCount: 96, documentsCount: 302, pendingHandovers: 0, openSnags: 18, upcomingAppointments: 4 },
    archived: false,
    createdAt: '2024-10-15T09:00:00Z',
    updatedAt: '2026-07-06T15:00:00Z',
  },
  {
    id: 'proj-008',
    name: 'Willow Creek Villas',
    code: 'WCV-08',
    description: 'Archived — replaced by a revised master plan.',
    organizationId: 'org-current',
    organizationName: 'Apex Developments',
    status: 'planning',
    constructionStage: 'land-acquisition',
    health: 'delayed',
    progress: 3,
    location: { addressLine: '2 Willow Creek Lane', city: 'Chandigarh', state: 'Punjab', postalCode: '160002', country: 'India' },
    startDate: '2024-01-01',
    targetCompletionDate: '2026-12-31',
    milestones: [
      { id: 'm1', label: 'Land acquisition', date: '2024-01-01', status: 'in-progress' },
    ],
    summary: { unitsTotal: 40, unitsSold: 0, ownersCount: 0, documentsCount: 6, pendingHandovers: 0, openSnags: 0, upcomingAppointments: 0 },
    archived: true,
    createdAt: '2023-12-01T09:00:00Z',
    updatedAt: '2025-03-01T09:00:00Z',
  },
];
