import { BrandConfiguration } from '../models';
import { DesignTokens } from '../models/design-token.model';

export const PLATFORM_DESIGN_TOKENS: DesignTokens = {
  colors: {
    primary: '#1a56db',
    primaryHover: '#1648b8',
    primaryContrast: '#ffffff',
    primarySubtle: '#eff6ff',
    secondary: '#475569',
    secondaryHover: '#1e293b',
    secondaryContrast: '#ffffff',
    accent: '#0ea5e9',
    accentHover: '#0284c7',
    accentContrast: '#ffffff',
    success: '#16a34a',
    successContrast: '#ffffff',
    warning: '#d97706',
    warningContrast: '#ffffff',
    danger: '#dc2626',
    dangerContrast: '#ffffff',
    info: '#2563eb',
    infoContrast: '#ffffff',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    surfaceMuted: '#f8fafc',
    background: '#f4f6f9',
    text: '#0f172a',
    textMuted: '#64748b',
    border: '#e8edf3',
    borderStrong: '#d5dde8',
    focus: '#1a56db',
  },
  shadows: {
    sm: '0 1px 2px rgb(15 23 42 / 4%), 0 1px 1px rgb(15 23 42 / 2%)',
    md: '0 4px 6px -1px rgb(15 23 42 / 6%), 0 2px 4px -2px rgb(15 23 42 / 4%)',
    lg: '0 10px 15px -3px rgb(15 23 42 / 8%), 0 4px 6px -4px rgb(15 23 42 / 4%)',
    xl: '0 20px 25px -5px rgb(15 23 42 / 8%), 0 8px 10px -6px rgb(15 23 42 / 4%)',
  },
  opacity: {
    disabled: 0.45,
    muted: 0.72,
    overlay: 0.45,
    hover: 0.08,
  },
  spacing: {
    unit: '0.25rem',
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
  },
  borderRadius: {
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
  typography: {
    fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
    fontFamilyMono: "ui-monospace, 'Cascadia Code', monospace",
    fontSizeXs: '0.75rem',
    fontSizeSm: '0.875rem',
    fontSizeMd: '1rem',
    fontSizeLg: '1.125rem',
    fontSizeXl: '1.25rem',
    fontSize2xl: '1.5rem',
    fontSize3xl: '1.875rem',
    lineHeightTight: '1.25',
    lineHeightNormal: '1.5',
    lineHeightRelaxed: '1.75',
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightSemibold: 600,
    fontWeightBold: 700,
  },
  elevation: {
    none: 'none',
    sm: '0 1px 2px rgb(15 23 42 / 4%), 0 1px 1px rgb(15 23 42 / 2%)',
    md: '0 4px 6px -1px rgb(15 23 42 / 6%), 0 2px 4px -2px rgb(15 23 42 / 4%)',
    lg: '0 10px 15px -3px rgb(15 23 42 / 8%), 0 4px 6px -4px rgb(15 23 42 / 4%)',
    xl: '0 20px 25px -5px rgb(15 23 42 / 8%), 0 8px 10px -6px rgb(15 23 42 / 4%)',
  },
  animation: {
    durationFast: '150ms',
    durationNormal: '250ms',
    durationSlow: '400ms',
    easingStandard: 'cubic-bezier(0.4, 0, 0.2, 1)',
    easingEmphasized: 'cubic-bezier(0.2, 0, 0, 1)',
  },
  transition: {
    fast: '150ms cubic-bezier(0.4, 0, 0.2, 1)',
    normal: '250ms cubic-bezier(0.4, 0, 0.2, 1)',
    slow: '400ms cubic-bezier(0.4, 0, 0.2, 1)',
  },
  zIndex: {
    base: 0,
    dropdown: 100,
    sticky: 200,
    overlay: 900,
    drawer: 950,
    modal: 1000,
    toast: 1100,
    tooltip: 1200,
  },
  iconSize: {
    sm: '1rem',
    md: '1.25rem',
    lg: '1.5rem',
    xl: '2rem',
  },
};

export const PLATFORM_DARK_TOKENS: Partial<DesignTokens> = {
  colors: {
    ...PLATFORM_DESIGN_TOKENS.colors,
    primarySubtle: '#172554',
    surface: '#0f172a',
    surfaceElevated: '#1e293b',
    surfaceMuted: '#1e293b',
    background: '#020617',
    text: '#f8fafc',
    textMuted: '#94a3b8',
    border: '#334155',
    borderStrong: '#475569',
  },
};

export const PLATFORM_BRAND: BrandConfiguration = {
  id: 'platform-default',
  type: 'platform',
  name: 'MyPropertyAsset',
  shortName: 'MPA',
  favicon: 'favicon.ico',
  primaryColor: PLATFORM_DESIGN_TOKENS.colors.primary,
  secondaryColor: PLATFORM_DESIGN_TOKENS.colors.secondary,
  accentColor: PLATFORM_DESIGN_TOKENS.colors.accent,
  logo: {
    src: 'assets/branding/platform/logo.svg',
    alt: 'MyPropertyAsset',
    width: 160,
    height: 40,
  },
  logoVariants: {
    light: {
      src: 'assets/branding/platform/logo-light.svg',
      alt: 'MyPropertyAsset',
    },
    dark: {
      src: 'assets/branding/platform/logo-dark.svg',
      alt: 'MyPropertyAsset',
    },
    compact: {
      src: 'assets/branding/platform/logo-compact.svg',
      alt: 'MPA',
    },
    loading: {
      src: 'assets/branding/platform/logo-loading.svg',
      alt: 'Loading MyPropertyAsset',
    },
  },
  loadingLogo: {
    src: 'assets/branding/platform/logo-loading.svg',
    alt: 'Loading MyPropertyAsset',
  },
  browserThemeColor: PLATFORM_DESIGN_TOKENS.colors.primary,
  manifest: {
    name: 'MyPropertyAsset',
    shortName: 'MPA',
    themeColor: PLATFORM_DESIGN_TOKENS.colors.primary,
    backgroundColor: PLATFORM_DESIGN_TOKENS.colors.surface,
  },
  emailBranding: {
    headerBackgroundColor: PLATFORM_DESIGN_TOKENS.colors.primary,
    footerTextColor: PLATFORM_DESIGN_TOKENS.colors.textMuted,
    logoUrl: 'assets/branding/platform/logo.svg',
  },
};

export const THEME_ENGINE_CONFIG = {
  defaultThemeId: 'platform-default',
  persistenceKey: 'mpa-theme-preference',
  supportedModes: ['light', 'dark', 'auto', 'system'] as const,
  allowOrganizationOverride: true,
};
